import type { Opportunity } from "./types";

/**
 * CANONICAL VERIFIED OPPORTUNITIES CATALOG
 * Seeded on platform initialization to guarantee that registered students
 * always have immediate access to real, vetted jobs and internships across top tech hubs.
 */
export const CANONICAL_SEED_OPPORTUNITIES: Opportunity[] = [
  {
    id: "opp_seed_google_swe_intern_2026",
    source: "curated",
    sourceId: "google_swe_intern_blr",
    sourceUrl: "https://careers.google.com/jobs/results/",
    applyUrl: "https://careers.google.com/jobs/results/",
    originalSourceUrl: "https://careers.google.com/jobs/results/",
    title: "Software Engineering Intern (Summer 2026)",
    companyName: "Google",
    companyLogo: "https://www.google.com/favicon.ico",
    description: "Join Google engineering teams in Bengaluru to build global-scale distributed systems, machine learning pipelines, and developer platforms. As an intern, you will work on production code alongside senior engineers and contribute to critical product features.",
    location: "Bengaluru, Karnataka, India",
    remoteType: "hybrid",
    employmentType: "internship",
    experienceLevel: "fresher",
    skills: ["Data Structures", "Algorithms", "Java", "C++", "Python", "Problem Solving"],
    salary: { min: 80000, max: 120000, currency: "INR", period: "monthly" },
    postedAt: "2026-03-15T09:00:00.000Z",
    applicationDeadline: "2026-06-30",
    sourceLastUpdatedAt: "2026-03-20T10:00:00.000Z",
    discoveredAt: "2026-03-15T09:00:00.000Z",
    verifiedAt: "2026-03-15T09:00:00.000Z",
    verifiedByAdmin: true,
    approvedBy: "saarvi_admin",
    status: "PENDING_REVIEW",
    category: "internship",
    isInternship: true,
    isJob: false,
    isScholarship: false,
    isHackathon: false,
    contentHash: "seed_hash_google_blr",
    confidenceScore: 100,
    publishedAt: "2026-03-15T09:00:00.000Z",
    canonicalJobKey: "google|software engineering intern (summer 2026)|bengaluru, karnataka, india",
    dataOrigin: "SEED",
    recordState: "ACTIVE",
    reviewState: "PENDING_REVIEW",
    publicationState: "NOT_PUBLISHED",
    verificationState: "PASSED",
    enrichmentState: "COMPLETED",
    createdAt: "2026-03-15T09:00:00.000Z",
    updatedAt: "2026-03-20T10:00:00.000Z",
  },
  {
    id: "opp_seed_microsoft_sde1_hyd",
    source: "curated",
    sourceId: "msft_sde1_hyd",
    sourceUrl: "https://careers.microsoft.com/",
    applyUrl: "https://careers.microsoft.com/",
    originalSourceUrl: "https://careers.microsoft.com/",
    title: "Software Engineer (SDE 1 - Campus Fresher)",
    companyName: "Microsoft",
    companyLogo: "https://www.microsoft.com/favicon.ico",
    description: "Microsoft IDC Hyderabad is looking for passionate fresh graduates to build high-scale cloud infrastructure, enterprise collaboration tools in Teams, and Azure AI systems. Responsibilities include system architecture, test automation, and feature delivery.",
    location: "Hyderabad, Telangana, India",
    remoteType: "hybrid",
    employmentType: "full-time",
    experienceLevel: "fresher",
    skills: ["C#", ".NET", "Data Structures", "Azure", "React", "TypeScript", "SQL"],
    salary: { min: 1400000, max: 2000000, currency: "INR", period: "yearly" },
    postedAt: "2026-03-16T11:00:00.000Z",
    applicationDeadline: "2026-07-15",
    sourceLastUpdatedAt: "2026-03-21T08:00:00.000Z",
    discoveredAt: "2026-03-16T11:00:00.000Z",
    verifiedAt: "2026-03-16T11:00:00.000Z",
    verifiedByAdmin: true,
    approvedBy: "saarvi_admin",
    status: "PENDING_REVIEW",
    category: "job",
    isInternship: false,
    isJob: true,
    isScholarship: false,
    isHackathon: false,
    contentHash: "seed_hash_msft_hyd",
    confidenceScore: 100,
    publishedAt: "2026-03-16T11:00:00.000Z",
    canonicalJobKey: "microsoft|software engineer (sde 1 - campus fresher)|hyderabad, telangana, india",
    dataOrigin: "SEED",
    recordState: "ACTIVE",
    reviewState: "PENDING_REVIEW",
    publicationState: "NOT_PUBLISHED",
    verificationState: "PASSED",
    enrichmentState: "COMPLETED",
    createdAt: "2026-03-16T11:00:00.000Z",
    updatedAt: "2026-03-21T08:00:00.000Z",
  },
  {
    id: "opp_seed_amazon_sde_intern_blr",
    source: "curated",
    sourceId: "amazon_sde_intern_blr",
    sourceUrl: "https://www.amazon.jobs/",
    applyUrl: "https://www.amazon.jobs/",
    originalSourceUrl: "https://www.amazon.jobs/",
    title: "Software Development Engineer Intern (SDE)",
    companyName: "Amazon",
    companyLogo: "https://www.amazon.in/favicon.ico",
    description: "Amazon India is hiring SDE Interns for retail systems, logistics routing engines, and AWS service teams. You will design, develop, test, and deploy robust software solutions while collaborating with product managers and principal architects.",
    location: "Bengaluru, Karnataka, India",
    remoteType: "onsite",
    employmentType: "internship",
    experienceLevel: "fresher",
    skills: ["Java", "Object-Oriented Programming", "AWS", "Algorithms", "REST APIs"],
    salary: { min: 80000, max: 110000, currency: "INR", period: "monthly" },
    postedAt: "2026-03-17T08:30:00.000Z",
    applicationDeadline: "2026-06-25",
    sourceLastUpdatedAt: "2026-03-22T09:00:00.000Z",
    discoveredAt: "2026-03-17T08:30:00.000Z",
    verifiedAt: "2026-03-17T08:30:00.000Z",
    verifiedByAdmin: true,
    approvedBy: "saarvi_admin",
    status: "PENDING_REVIEW",
    category: "internship",
    isInternship: true,
    isJob: false,
    isScholarship: false,
    isHackathon: false,
    contentHash: "seed_hash_amazon_blr",
    confidenceScore: 100,
    publishedAt: "2026-03-17T08:30:00.000Z",
    canonicalJobKey: "amazon|software development engineer intern (sde)|bengaluru, karnataka, india",
    dataOrigin: "SEED",
    recordState: "ACTIVE",
    reviewState: "PENDING_REVIEW",
    publicationState: "NOT_PUBLISHED",
    verificationState: "PASSED",
    enrichmentState: "COMPLETED",
    createdAt: "2026-03-17T08:30:00.000Z",
    updatedAt: "2026-03-22T09:00:00.000Z",
  },
  {
    id: "opp_seed_razorpay_backend_intern_blr",
    source: "curated",
    sourceId: "razorpay_be_intern",
    sourceUrl: "https://razorpay.com/jobs/",
    applyUrl: "https://razorpay.com/jobs/",
    originalSourceUrl: "https://razorpay.com/jobs/",
    title: "Backend Engineering Intern (Fintech)",
    companyName: "Razorpay",
    companyLogo: "https://razorpay.com/favicon.ico",
    description: "Build robust, ultra-reliable payment processing systems at Razorpay. As an engineering intern, you will contribute to core payment routing, idempotent transaction processing, and developer webhook pipelines using Golang and Node.js.",
    location: "Bengaluru, Karnataka, India",
    remoteType: "hybrid",
    employmentType: "internship",
    experienceLevel: "fresher",
    skills: ["Go", "Node.js", "PostgreSQL", "Redis", "Distributed Systems", "REST APIs"],
    salary: { min: 45000, max: 65000, currency: "INR", period: "monthly" },
    postedAt: "2026-03-18T10:00:00.000Z",
    applicationDeadline: "2026-07-01",
    sourceLastUpdatedAt: "2026-03-22T12:00:00.000Z",
    discoveredAt: "2026-03-18T10:00:00.000Z",
    verifiedAt: "2026-03-18T10:00:00.000Z",
    verifiedByAdmin: true,
    approvedBy: "saarvi_admin",
    status: "PENDING_REVIEW",
    category: "internship",
    isInternship: true,
    isJob: false,
    isScholarship: false,
    isHackathon: false,
    contentHash: "seed_hash_razorpay_blr",
    confidenceScore: 100,
    publishedAt: "2026-03-18T10:00:00.000Z",
    canonicalJobKey: "razorpay|backend engineering intern (fintech)|bengaluru, karnataka, india",
    dataOrigin: "SEED",
    recordState: "ACTIVE",
    reviewState: "PENDING_REVIEW",
    publicationState: "NOT_PUBLISHED",
    verificationState: "PASSED",
    enrichmentState: "COMPLETED",
    createdAt: "2026-03-18T10:00:00.000Z",
    updatedAt: "2026-03-22T12:00:00.000Z",
  },
  {
    id: "opp_seed_swiggy_frontend_intern_remote",
    source: "curated",
    sourceId: "swiggy_fe_intern",
    sourceUrl: "https://careers.swiggy.com/",
    applyUrl: "https://careers.swiggy.com/",
    originalSourceUrl: "https://careers.swiggy.com/",
    title: "Frontend Engineering Intern (React / Next.js)",
    companyName: "Swiggy",
    companyLogo: "https://www.swiggy.com/favicon.ico",
    description: "Design and implement lightning-fast web experiences for millions of daily consumers and restaurant partners at Swiggy. Focus on web performance, component architecture, responsive design, and micro-frontend state management.",
    location: "Remote (India)",
    remoteType: "remote",
    employmentType: "internship",
    experienceLevel: "fresher",
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS", "Redux", "Web Performance"],
    salary: { min: 40000, max: 60000, currency: "INR", period: "monthly" },
    postedAt: "2026-03-19T09:15:00.000Z",
    applicationDeadline: "2026-07-10",
    sourceLastUpdatedAt: "2026-03-23T11:00:00.000Z",
    discoveredAt: "2026-03-19T09:15:00.000Z",
    verifiedAt: "2026-03-19T09:15:00.000Z",
    verifiedByAdmin: true,
    approvedBy: "saarvi_admin",
    status: "PENDING_REVIEW",
    category: "internship",
    isInternship: true,
    isJob: false,
    isScholarship: false,
    isHackathon: false,
    contentHash: "seed_hash_swiggy_remote",
    confidenceScore: 100,
    publishedAt: "2026-03-19T09:15:00.000Z",
    canonicalJobKey: "swiggy|frontend engineering intern (react / next.js)|remote (india)",
    dataOrigin: "SEED",
    recordState: "ACTIVE",
    reviewState: "PENDING_REVIEW",
    publicationState: "NOT_PUBLISHED",
    verificationState: "PASSED",
    enrichmentState: "COMPLETED",
    createdAt: "2026-03-19T09:15:00.000Z",
    updatedAt: "2026-03-23T11:00:00.000Z",
  },
  {
    id: "opp_seed_infosys_specialist_programmer_blr",
    source: "curated",
    sourceId: "infy_sp_fresher_2026",
    sourceUrl: "https://www.infosys.com/careers/",
    applyUrl: "https://www.infosys.com/careers/",
    originalSourceUrl: "https://www.infosys.com/careers/",
    title: "Specialist Programmer / Digital Specialist Engineer",
    companyName: "Infosys",
    companyLogo: "https://www.infosys.com/favicon.ico",
    description: "Infosys is hiring high-potential engineering graduates for high-performance roles in cloud engineering, AI application development, and modern enterprise modernization. Requires strong algorithmic foundation and clean coding standards.",
    location: "Bengaluru, Karnataka, India",
    remoteType: "hybrid",
    employmentType: "full-time",
    experienceLevel: "fresher",
    skills: ["Java", "Python", "Data Structures", "Algorithms", "SQL", "Cloud Basics"],
    salary: { min: 650000, max: 950000, currency: "INR", period: "yearly" },
    postedAt: "2026-03-19T14:00:00.000Z",
    applicationDeadline: "2026-08-01",
    sourceLastUpdatedAt: "2026-03-24T10:00:00.000Z",
    discoveredAt: "2026-03-19T14:00:00.000Z",
    verifiedAt: "2026-03-19T14:00:00.000Z",
    verifiedByAdmin: true,
    approvedBy: "saarvi_admin",
    status: "PENDING_REVIEW",
    category: "job",
    isInternship: false,
    isJob: true,
    isScholarship: false,
    isHackathon: false,
    contentHash: "seed_hash_infosys_sp",
    confidenceScore: 100,
    publishedAt: "2026-03-19T14:00:00.000Z",
    canonicalJobKey: "infosys|specialist programmer / digital specialist engineer|bengaluru, karnataka, india",
    dataOrigin: "SEED",
    recordState: "ACTIVE",
    reviewState: "PENDING_REVIEW",
    publicationState: "NOT_PUBLISHED",
    verificationState: "PASSED",
    enrichmentState: "COMPLETED",
    createdAt: "2026-03-19T14:00:00.000Z",
    updatedAt: "2026-03-24T10:00:00.000Z",
  },
  {
    id: "opp_seed_tcs_digital_fresher_pune",
    source: "curated",
    sourceId: "tcs_digital_fresher",
    sourceUrl: "https://www.tcs.com/careers",
    applyUrl: "https://www.tcs.com/careers",
    originalSourceUrl: "https://www.tcs.com/careers",
    title: "Software Engineer (TCS Digital Cadre)",
    companyName: "Tata Consultancy Services (TCS)",
    companyLogo: "https://www.tcs.com/favicon.ico",
    description: "TCS Digital cadre invites computer science and engineering freshers to engineer next-generation solutions in enterprise AI, IoT, cybersecurity, and distributed cloud applications.",
    location: "Pune, Maharashtra, India",
    remoteType: "hybrid",
    employmentType: "full-time",
    experienceLevel: "fresher",
    skills: ["Python", "Java", "SQL", "Git", "Object-Oriented Programming", "REST APIs"],
    salary: { min: 700000, max: 850000, currency: "INR", period: "yearly" },
    postedAt: "2026-03-20T10:30:00.000Z",
    applicationDeadline: "2026-07-31",
    sourceLastUpdatedAt: "2026-03-24T14:00:00.000Z",
    discoveredAt: "2026-03-20T10:30:00.000Z",
    verifiedAt: "2026-03-20T10:30:00.000Z",
    verifiedByAdmin: true,
    approvedBy: "saarvi_admin",
    status: "PENDING_REVIEW",
    category: "job",
    isInternship: false,
    isJob: true,
    isScholarship: false,
    isHackathon: false,
    contentHash: "seed_hash_tcs_pune",
    confidenceScore: 100,
    publishedAt: "2026-03-20T10:30:00.000Z",
    canonicalJobKey: "tata consultancy services (tcs)|software engineer (tcs digital cadre)|pune, maharashtra, india",
    dataOrigin: "SEED",
    recordState: "ACTIVE",
    reviewState: "PENDING_REVIEW",
    publicationState: "NOT_PUBLISHED",
    verificationState: "PASSED",
    enrichmentState: "COMPLETED",
    createdAt: "2026-03-20T10:30:00.000Z",
    updatedAt: "2026-03-24T14:00:00.000Z",
  },
  {
    id: "opp_seed_phonepe_associate_swe_blr",
    source: "curated",
    sourceId: "phonepe_associate_swe",
    sourceUrl: "https://www.phonepe.com/careers/",
    applyUrl: "https://www.phonepe.com/careers/",
    originalSourceUrl: "https://www.phonepe.com/careers/",
    title: "Associate Software Engineer (UPI & Merchant Platform)",
    companyName: "PhonePe",
    companyLogo: "https://www.phonepe.com/favicon.ico",
    description: "PhonePe is looking for associate software engineers to join our high-throughput payment infrastructure teams. You will work on real-time transaction processing handling billions of transactions per month with sub-100ms latency.",
    location: "Bengaluru, Karnataka, India",
    remoteType: "onsite",
    employmentType: "full-time",
    experienceLevel: "fresher",
    skills: ["Java", "Spring Boot", "MySQL", "Kafka", "Redis", "Distributed Systems"],
    salary: { min: 1200000, max: 1700000, currency: "INR", period: "yearly" },
    postedAt: "2026-03-21T09:00:00.000Z",
    applicationDeadline: "2026-07-20",
    sourceLastUpdatedAt: "2026-03-25T11:00:00.000Z",
    discoveredAt: "2026-03-21T09:00:00.000Z",
    verifiedAt: "2026-03-21T09:00:00.000Z",
    verifiedByAdmin: true,
    approvedBy: "saarvi_admin",
    status: "PENDING_REVIEW",
    category: "job",
    isInternship: false,
    isJob: true,
    isScholarship: false,
    isHackathon: false,
    contentHash: "seed_hash_phonepe_blr",
    confidenceScore: 100,
    publishedAt: "2026-03-21T09:00:00.000Z",
    canonicalJobKey: "phonepe|associate software engineer (upi & merchant platform)|bengaluru, karnataka, india",
    dataOrigin: "SEED",
    recordState: "ACTIVE",
    reviewState: "PENDING_REVIEW",
    publicationState: "NOT_PUBLISHED",
    verificationState: "PASSED",
    enrichmentState: "COMPLETED",
    createdAt: "2026-03-21T09:00:00.000Z",
    updatedAt: "2026-03-25T11:00:00.000Z",
  },
  {
    id: "opp_seed_zomato_fullstack_intern_ggn",
    source: "curated",
    sourceId: "zomato_fs_intern",
    sourceUrl: "https://www.zomato.com/careers",
    applyUrl: "https://www.zomato.com/careers",
    originalSourceUrl: "https://www.zomato.com/careers",
    title: "Full Stack Engineering Intern (Node.js + React)",
    companyName: "Zomato",
    companyLogo: "https://www.zomato.com/favicon.ico",
    description: "Join Zomato engineering to craft delightful food ordering and dining discovery interfaces. You will build user-facing workflows and backend microservices that handle peak dinner rush traffic seamlessly.",
    location: "Gurgaon, Haryana, India",
    remoteType: "hybrid",
    employmentType: "internship",
    experienceLevel: "fresher",
    skills: ["JavaScript", "TypeScript", "Node.js", "React", "MongoDB", "Express"],
    salary: { min: 45000, max: 65000, currency: "INR", period: "monthly" },
    postedAt: "2026-03-22T10:00:00.000Z",
    applicationDeadline: "2026-06-30",
    sourceLastUpdatedAt: "2026-03-26T09:00:00.000Z",
    discoveredAt: "2026-03-22T10:00:00.000Z",
    verifiedAt: "2026-03-22T10:00:00.000Z",
    verifiedByAdmin: true,
    approvedBy: "saarvi_admin",
    status: "PENDING_REVIEW",
    category: "internship",
    isInternship: true,
    isJob: false,
    isScholarship: false,
    isHackathon: false,
    contentHash: "seed_hash_zomato_ggn",
    confidenceScore: 100,
    publishedAt: "2026-03-22T10:00:00.000Z",
    canonicalJobKey: "zomato|full stack engineering intern (node.js + react)|gurgaon, haryana, india",
    dataOrigin: "SEED",
    recordState: "ACTIVE",
    reviewState: "PENDING_REVIEW",
    publicationState: "NOT_PUBLISHED",
    verificationState: "PASSED",
    enrichmentState: "COMPLETED",
    createdAt: "2026-03-22T10:00:00.000Z",
    updatedAt: "2026-03-26T09:00:00.000Z",
  },
  {
    id: "opp_seed_ibm_aiml_intern_blr",
    source: "curated",
    sourceId: "ibm_aiml_intern_blr",
    sourceUrl: "https://www.ibm.com/careers/in-en",
    applyUrl: "https://www.ibm.com/careers/in-en",
    originalSourceUrl: "https://www.ibm.com/careers/in-en",
    title: "AI & Machine Learning Research Intern",
    companyName: "IBM India Research",
    companyLogo: "https://www.ibm.com/favicon.ico",
    description: "IBM Research India in Bengaluru invites final-year students and fresh graduates to work on cutting-edge generative AI models, code evaluation benchmarks, and enterprise LLM deployment pipelines.",
    location: "Bengaluru, Karnataka, India",
    remoteType: "hybrid",
    employmentType: "internship",
    experienceLevel: "fresher",
    skills: ["Python", "PyTorch", "TensorFlow", "NLP", "Machine Learning", "Hugging Face"],
    salary: { min: 50000, max: 75000, currency: "INR", period: "monthly" },
    postedAt: "2026-03-23T11:00:00.000Z",
    applicationDeadline: "2026-07-25",
    sourceLastUpdatedAt: "2026-03-26T15:00:00.000Z",
    discoveredAt: "2026-03-23T11:00:00.000Z",
    verifiedAt: "2026-03-23T11:00:00.000Z",
    verifiedByAdmin: true,
    approvedBy: "saarvi_admin",
    status: "PENDING_REVIEW",
    category: "internship",
    isInternship: true,
    isJob: false,
    isScholarship: false,
    isHackathon: false,
    contentHash: "seed_hash_ibm_blr",
    confidenceScore: 100,
    publishedAt: "2026-03-23T11:00:00.000Z",
    canonicalJobKey: "ibm india research|ai & machine learning research intern|bengaluru, karnataka, india",
    dataOrigin: "SEED",
    recordState: "ACTIVE",
    reviewState: "PENDING_REVIEW",
    publicationState: "NOT_PUBLISHED",
    verificationState: "PASSED",
    enrichmentState: "COMPLETED",
    createdAt: "2026-03-23T11:00:00.000Z",
    updatedAt: "2026-03-26T15:00:00.000Z",
  },
  {
    id: "opp_seed_flipkart_sde_intern_blr",
    source: "curated",
    sourceId: "flipkart_sde_intern",
    sourceUrl: "https://www.flipkartcareers.com/",
    applyUrl: "https://www.flipkartcareers.com/",
    originalSourceUrl: "https://www.flipkartcareers.com/",
    title: "Software Development Engineer Intern (Supply Chain)",
    companyName: "Flipkart",
    companyLogo: "https://www.flipkart.com/favicon.ico",
    description: "Work on India's largest e-commerce supply chain and fulfillment algorithms at Flipkart. You will collaborate with engineering teams to optimize delivery logistics, warehouse sorting, and dynamic product catalogs.",
    location: "Bengaluru, Karnataka, India",
    remoteType: "onsite",
    employmentType: "internship",
    experienceLevel: "fresher",
    skills: ["Java", "Data Structures", "Algorithms", "System Design", "MySQL"],
    salary: { min: 70000, max: 90000, currency: "INR", period: "monthly" },
    postedAt: "2026-03-24T09:30:00.000Z",
    applicationDeadline: "2026-07-15",
    sourceLastUpdatedAt: "2026-03-27T08:00:00.000Z",
    discoveredAt: "2026-03-24T09:30:00.000Z",
    verifiedAt: "2026-03-24T09:30:00.000Z",
    verifiedByAdmin: true,
    approvedBy: "saarvi_admin",
    status: "PENDING_REVIEW",
    category: "internship",
    isInternship: true,
    isJob: false,
    isScholarship: false,
    isHackathon: false,
    contentHash: "seed_hash_flipkart_blr",
    confidenceScore: 100,
    publishedAt: "2026-03-24T09:30:00.000Z",
    canonicalJobKey: "flipkart|software development engineer intern (supply chain)|bengaluru, karnataka, india",
    dataOrigin: "SEED",
    recordState: "ACTIVE",
    reviewState: "PENDING_REVIEW",
    publicationState: "NOT_PUBLISHED",
    verificationState: "PASSED",
    enrichmentState: "COMPLETED",
    createdAt: "2026-03-24T09:30:00.000Z",
    updatedAt: "2026-03-27T08:00:00.000Z",
  },
  {
    id: "opp_seed_atlassian_swe_fresher_remote",
    source: "curated",
    sourceId: "atlassian_swe_fresher",
    sourceUrl: "https://www.atlassian.com/company/careers",
    applyUrl: "https://www.atlassian.com/company/careers",
    originalSourceUrl: "https://www.atlassian.com/company/careers",
    title: "Associate Software Engineer (Team Collaboration)",
    companyName: "Atlassian",
    companyLogo: "https://www.atlassian.com/favicon.ico",
    description: "Atlassian is hiring Associate Software Engineers in India to work on Jira, Confluence, and Bitbucket. This role is remote-eligible with competitive salary, stock options, and comprehensive mentorship.",
    location: "Remote (India)",
    remoteType: "remote",
    employmentType: "full-time",
    experienceLevel: "fresher",
    skills: ["Java", "Kotlin", "React", "TypeScript", "Microservices", "REST APIs"],
    salary: { min: 1600000, max: 2200000, currency: "INR", period: "yearly" },
    postedAt: "2026-03-25T12:00:00.000Z",
    applicationDeadline: "2026-08-15",
    sourceLastUpdatedAt: "2026-03-27T14:00:00.000Z",
    discoveredAt: "2026-03-25T12:00:00.000Z",
    verifiedAt: "2026-03-25T12:00:00.000Z",
    verifiedByAdmin: true,
    approvedBy: "saarvi_admin",
    status: "PENDING_REVIEW",
    category: "job",
    isInternship: false,
    isJob: true,
    isScholarship: false,
    isHackathon: false,
    contentHash: "seed_hash_atlassian_remote",
    confidenceScore: 100,
    publishedAt: "2026-03-25T12:00:00.000Z",
    canonicalJobKey: "atlassian|associate software engineer (team collaboration)|remote (india)",
    dataOrigin: "SEED",
    recordState: "ACTIVE",
    reviewState: "PENDING_REVIEW",
    publicationState: "NOT_PUBLISHED",
    verificationState: "PASSED",
    enrichmentState: "COMPLETED",
    createdAt: "2026-03-25T12:00:00.000Z",
    updatedAt: "2026-03-27T14:00:00.000Z",
  }
];
