// DocEase Phase 12: Central Feature Registry & Limits Configuration
// Single source of truth for platform feature capabilities, plan requirements, and privacy processing types.

import { FeatureDefinition, Plan, PlanLimits, FeatureId } from '@/types/plan';

export const PLAN_LIMITS: Record<Plan, PlanLimits> = {
  guest: {
    plan: 'guest',
    displayName: 'Guest (No Account)',
    maxFileSizeMB: 50, // Physical browser memory safety limit
    maxBatchFiles: 10,
    maxPagesPerPdf: 100,
    batchProcessingEnabled: false,
    premiumTemplatesEnabled: false,
    aiAssistantEnabled: false,
    ocrEnabled: false,
    cloudSyncEnabled: false,
    apiAccessEnabled: false,
  },
  free: {
    plan: 'free',
    displayName: 'Free Account',
    maxFileSizeMB: 50,
    maxBatchFiles: 20,
    maxPagesPerPdf: 150,
    batchProcessingEnabled: false,
    premiumTemplatesEnabled: false,
    aiAssistantEnabled: false,
    ocrEnabled: false,
    cloudSyncEnabled: false,
    apiAccessEnabled: false,
  },
  pro: {
    plan: 'pro',
    displayName: 'Saarvi Pro (Coming Soon)',
    maxFileSizeMB: 100, // Conceptual planned limit
    maxBatchFiles: 50,
    maxPagesPerPdf: 500,
    batchProcessingEnabled: true,
    premiumTemplatesEnabled: true,
    aiAssistantEnabled: true,
    ocrEnabled: true,
    cloudSyncEnabled: true,
    apiAccessEnabled: true,
  },
};

export const FEATURES_REGISTRY: Record<FeatureId, FeatureDefinition> = {
  // =========================================================================
  // 1. PUBLIC BASIC DOCUMENT TOOLS (GUEST / FREE / PRO - 100% CLIENT LOCAL)
  // =========================================================================
  jpg_to_pdf: {
    id: 'jpg_to_pdf',
    name: 'JPG to PDF',
    category: 'document',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Convert JPG photos into standard PDF documents entirely in browser.',
    toolSlug: 'jpg-to-pdf',
  },
  pdf_to_jpg: {
    id: 'pdf_to_jpg',
    name: 'PDF to JPG',
    category: 'document',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Render and extract high-resolution JPG images from PDF pages locally.',
    toolSlug: 'pdf-to-jpg',
  },
  png_to_jpg: {
    id: 'png_to_jpg',
    name: 'PNG to JPG',
    category: 'document',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Convert transparent PNG graphics into lightweight JPG images.',
    toolSlug: 'png-to-jpg',
  },
  jpg_to_png: {
    id: 'jpg_to_png',
    name: 'JPG to PNG',
    category: 'document',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Convert compressed JPG files into lossless PNG format.',
    toolSlug: 'jpg-to-png',
  },
  image_to_pdf: {
    id: 'image_to_pdf',
    name: 'Image to PDF',
    category: 'document',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Transform any standard graphic into a clean single-page PDF.',
    toolSlug: 'image-to-pdf',
  },
  multiple_images_to_pdf: {
    id: 'multiple_images_to_pdf',
    name: 'Multiple Images to PDF',
    category: 'document',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Combine multiple image files into a single multi-page PDF.',
    toolSlug: 'multiple-images-to-pdf',
  },
  image_resize: {
    id: 'image_resize',
    name: 'Resize Image',
    category: 'document',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Scale image dimensions by exact pixels or percentage with aspect ratio lock.',
    toolSlug: 'image-resize',
  },
  image_crop: {
    id: 'image_crop',
    name: 'Crop Image',
    category: 'document',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Trim canvas boundaries to exact dimensions with real-time preview.',
    toolSlug: 'image-crop',
  },
  image_rotate: {
    id: 'image_rotate',
    name: 'Rotate Image',
    category: 'document',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Rotate photos 90°, 180°, or 270° with lossless canvas export.',
    toolSlug: 'image-rotate',
  },
  image_compress: {
    id: 'image_compress',
    name: 'Compress Image',
    category: 'document',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Reduce image file size with adjustable compression quality.',
    toolSlug: 'image-compress',
  },
  merge_pdf: {
    id: 'merge_pdf',
    name: 'Merge PDF',
    category: 'document',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Combine multiple PDF files into one ordered master document.',
    toolSlug: 'merge-pdf',
  },
  split_pdf: {
    id: 'split_pdf',
    name: 'Split PDF',
    category: 'document',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Divide large PDF documents into smaller parts or separate pages.',
    toolSlug: 'split-pdf',
  },
  extract_pdf_pages: {
    id: 'extract_pdf_pages',
    name: 'Extract PDF Pages',
    category: 'document',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Extract specific pages or page ranges from a PDF document.',
    toolSlug: 'extract-pdf-pages',
  },
  rotate_pdf: {
    id: 'rotate_pdf',
    name: 'Rotate PDF',
    category: 'document',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Rotate individual or all pages of a PDF document.',
    toolSlug: 'rotate-pdf',
  },
  compress_pdf: {
    id: 'compress_pdf',
    name: 'Compress PDF',
    category: 'document',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Shrink PDF file size while preserving layout clarity.',
    toolSlug: 'compress-pdf',
  },
  organize_pdf: {
    id: 'organize_pdf',
    name: 'Organize PDF',
    category: 'document',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Reorder, delete, or duplicate pages in PDF documents.',
    toolSlug: 'organize-pdf',
  },

  // =========================================================================
  // 2. PUBLIC BASIC STUDENT TOOLS (GUEST / FREE / PRO - 100% CLIENT LOCAL)
  // =========================================================================
  vtu_sgpa: {
    id: 'vtu_sgpa',
    name: 'VTU SGPA Calculator',
    category: 'student',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'VTU 2022 Scheme semester grade point engine with adaptive CIE/SEE input.',
    toolSlug: 'vtu-sgpa',
  },
  vtu_cgpa: {
    id: 'vtu_cgpa',
    name: 'VTU CGPA & Percentage',
    category: 'student',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Cumulative GPA and official Karnataka percentage formula calculator.',
    toolSlug: 'vtu-cgpa',
  },
  attendance_calculator: {
    id: 'attendance_calculator',
    name: 'Attendance Manager',
    category: 'student',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Calculate bunkable classes or classes needed to hit 75%/85% targets.',
    toolSlug: 'attendance',
  },
  percentage_calculator: {
    id: 'percentage_calculator',
    name: 'Percentage Calculator',
    category: 'student',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Quick grade and percentage aggregator for semester marks.',
    toolSlug: 'percentage',
  },
  marks_calculator: {
    id: 'marks_calculator',
    name: 'VTU Marks Weightage Calculator',
    category: 'student',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Calculate 50:50 / 40:60 CIE & SEE weightage distributions.',
    toolSlug: 'marks-calculator',
  },
  resume_builder: {
    id: 'resume_builder',
    name: 'Student Resume Builder',
    category: 'student',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'ATS-optimized clean technical resume generator with instant PDF export.',
    toolSlug: 'resume-builder',
  },
  cover_letter_builder: {
    id: 'cover_letter_builder',
    name: 'Cover Letter Builder',
    category: 'student',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Targeted internship and graduate role cover letter generator.',
    toolSlug: 'cover-letter',
  },
  study_planner: {
    id: 'study_planner',
    name: 'Exam & Study Planner',
    category: 'student',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Subject task breakdown and study session scheduler.',
    toolSlug: 'study-planner',
  },
  assignment_tracker: {
    id: 'assignment_tracker',
    name: 'Assignment Tracker',
    category: 'student',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Deadline tracker with multi-criteria priority sorting.',
    toolSlug: 'assignment-tracker',
  },
  college_timetable: {
    id: 'college_timetable',
    name: 'College Timetable',
    category: 'student',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Weekly schedule planner with O(N log N) interval overlap conflict detector.',
    toolSlug: 'timetable',
  },
  certificate_organizer: {
    id: 'certificate_organizer',
    name: 'Certificate Organizer',
    category: 'student',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Credential vault with duplicate detection and verification metadata.',
    toolSlug: 'certificates',
  },
  internship_tracker: {
    id: 'internship_tracker',
    name: 'Internship Tracker',
    category: 'student',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Application pipeline tracker from Applied to Interview and Offer.',
    toolSlug: 'internships',
  },
  hackathon_tracker: {
    id: 'hackathon_tracker',
    name: 'Hackathon Tracker',
    category: 'student',
    requiredPlan: 'guest',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Registry for hackathon submissions, project repositories, and prizes.',
    toolSlug: 'hackathons',
  },

  // =========================================================================
  // 3. FREE ACCOUNT CONVENIENCE FEATURES (AUTHENTICATED FREE & PRO)
  // =========================================================================
  local_workspace: {
    id: 'local_workspace',
    name: 'Persistent Local Workspace',
    category: 'workspace',
    requiredPlan: 'free',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Associate local browser storage with your user profile.',
  },
  saved_preferences: {
    id: 'saved_preferences',
    name: 'Saved User Preferences',
    category: 'workspace',
    requiredPlan: 'free',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Automatic download preferences, default theme, and tool configurations.',
  },
  conversion_history: {
    id: 'conversion_history',
    name: 'Local Operation History',
    category: 'workspace',
    requiredPlan: 'free',
    enabled: true,
    availability: 'available',
    processingType: 'local',
    description: 'Private metadata history of completed local conversions on this device.',
  },

  // =========================================================================
  // 4. FUTURE PRO FEATURES (CONCEPTUAL / COMING SOON - DISABLED FOR MONETIZATION)
  // =========================================================================
  batch_processing: {
    id: 'batch_processing',
    name: 'Advanced Batch Processing',
    category: 'document',
    requiredPlan: 'pro',
    enabled: true,
    availability: 'pro',
    processingType: 'local',
    description: 'Convert, compress, and process up to 50 files simultaneously.',
    proNotice: 'Included with Saarvi Pro. High-throughput client-side batch queue.',
  },
  advanced_compression: {
    id: 'advanced_compression',
    name: 'Extreme Document Compression',
    category: 'document',
    requiredPlan: 'pro',
    enabled: false,
    availability: 'coming_soon',
    processingType: 'local',
    description: 'Deeper optimization algorithms for ultra-small PDF file footprints.',
    proNotice: 'Coming Soon with Saarvi Pro.',
  },
  pdf_page_editor: {
    id: 'pdf_page_editor',
    name: 'Visual PDF Page Editor',
    category: 'document',
    requiredPlan: 'pro',
    enabled: false,
    availability: 'coming_soon',
    processingType: 'local',
    description: 'Interactive page deletion, renumbering, and watermarking.',
    proNotice: 'Coming Soon with Saarvi Pro.',
  },
  premium_resume_templates: {
    id: 'premium_resume_templates',
    name: 'Premium ATS Resume Templates',
    category: 'student',
    requiredPlan: 'pro',
    enabled: true,
    availability: 'pro',
    processingType: 'local',
    description: 'Professional multi-column, executive, and specialized tech templates.',
    proNotice: 'Included with Saarvi Pro.',
  },
  career_portfolio_export: {
    id: 'career_portfolio_export',
    name: 'Career Portfolio Export',
    category: 'student',
    requiredPlan: 'pro',
    enabled: false,
    availability: 'coming_soon',
    processingType: 'local',
    description: 'Bundle resume, verified certificates, and project summaries into one link.',
    proNotice: 'Coming Soon with Saarvi Pro.',
  },
  image_ocr: {
    id: 'image_ocr',
    name: 'Image OCR Text Extractor',
    category: 'ocr',
    requiredPlan: 'pro',
    enabled: false,
    availability: 'coming_soon',
    processingType: 'mixed',
    description: 'Optical character recognition to extract editable text from images.',
    proNotice: 'Planned Pro feature. Privacy-safe OCR processing.',
  },
  scanned_pdf_ocr: {
    id: 'scanned_pdf_ocr',
    name: 'Scanned PDF Searchable OCR',
    category: 'ocr',
    requiredPlan: 'pro',
    enabled: false,
    availability: 'coming_soon',
    processingType: 'mixed',
    description: 'Embed searchable text layers into scanned image-only PDFs.',
    proNotice: 'Planned Pro feature.',
  },
  ai_resume_assistant: {
    id: 'ai_resume_assistant',
    name: 'AI Resume Bullet Enhancer',
    category: 'ai',
    requiredPlan: 'pro',
    enabled: false,
    availability: 'coming_soon',
    processingType: 'server',
    description: 'Action-verb enhancement and quantification suggestions for resumes.',
    proNotice: 'Planned Pro capability. Optical & generative AI assistants.',
  },
  ai_cover_letter: {
    id: 'ai_cover_letter',
    name: 'AI Cover Letter Generator',
    category: 'ai',
    requiredPlan: 'pro',
    enabled: false,
    availability: 'coming_soon',
    processingType: 'server',
    description: 'Tailored application letter drafting matching specific job descriptions.',
    proNotice: 'Planned Pro capability.',
  },
  ai_pdf_assistant: {
    id: 'ai_pdf_assistant',
    name: 'AI PDF Document Assistant',
    category: 'ai',
    requiredPlan: 'pro',
    enabled: false,
    availability: 'coming_soon',
    processingType: 'server',
    description: 'Ask questions and summarize content directly from complex PDFs.',
    proNotice: 'Planned Pro capability.',
  },
  ai_study_assistant: {
    id: 'ai_study_assistant',
    name: 'AI VTU Syllabus Study Assistant',
    category: 'ai',
    requiredPlan: 'pro',
    enabled: false,
    availability: 'coming_soon',
    processingType: 'server',
    description: 'Generate study questions and concept flashcards from syllabus modules.',
    proNotice: 'Planned Pro capability.',
  },
  cloud_sync: {
    id: 'cloud_sync',
    name: 'Cross-Device Workspace Sync',
    category: 'workspace',
    requiredPlan: 'pro',
    enabled: false,
    availability: 'coming_soon',
    processingType: 'server',
    description: 'Optional encrypted synchronization of drafts and student notes.',
    proNotice: 'Planned Pro capability.',
  },
  cross_device_workspace: {
    id: 'cross_device_workspace',
    name: 'Cross-Device Personal Workspace',
    category: 'workspace',
    requiredPlan: 'pro',
    enabled: false,
    availability: 'coming_soon',
    processingType: 'server',
    description: 'Seamlessly resume drafts between mobile, tablet, and desktop.',
    proNotice: 'Planned Pro capability.',
  },
  developer_api: {
    id: 'developer_api',
    name: 'Saarvi Developer API',
    category: 'developer',
    requiredPlan: 'pro',
    enabled: false,
    availability: 'coming_soon',
    processingType: 'server',
    description: 'Programmatic API keys for automated document conversions.',
    proNotice: 'Planned Pro capability.',
  },
};
