import { StudentToolConfig } from '@/types/admin';

export const STUDENT_TOOLS_REGISTRY: StudentToolConfig[] = [
  {
    id: 'vtu-sgpa',
    name: 'SGPA Calculator',
    category: 'academic',
    description: 'Official 2022 Scheme CIE + SEE and Continuous Evaluation engine',
    route: '/student/sgpa',
    status: 'available',
    featured: true,
    orderIndex: 1,
  },
  {
    id: 'vtu-cgpa',
    name: 'VTU CGPA & Percentage',
    category: 'academic',
    description: 'Cumulative grade point average with Karnataka state percentage formula',
    route: '/student/cgpa',
    status: 'available',
    featured: true,
    orderIndex: 2,
  },
  {
    id: 'attendance',
    name: 'Attendance Manager',
    category: 'planning',
    description: 'Safe class calculation and target attendance planner (75% / 85%)',
    route: '/student/attendance',
    status: 'available',
    featured: true,
    orderIndex: 3,
  },
  {
    id: 'career-dashboard',
    name: 'Career & Placement Suite',
    category: 'career',
    description: 'Unified career profile, multi-version resumes, skill gap analysis, and placement dashboard',
    route: '/student/career',
    status: 'available',
    featured: true,
    orderIndex: 4,
  },
  {
    id: 'resume-builder',
    name: 'Student Resume Builder',
    category: 'career',
    description: 'ATS-optimized clean technical resume builder with instant vector PDF export',
    route: '/student/resume',
    status: 'available',
    featured: true,
    orderIndex: 5,
  },
  {
    id: 'application-tracker',
    name: 'Job & Application Tracker',
    category: 'career',
    description: 'Application pipelines, scheduled interview reminders, and deadline alerts',
    route: '/student/applications',
    status: 'available',
    featured: true,
    orderIndex: 6,
  },
  {
    id: 'cover-letter',
    name: 'Cover Letter Builder',
    category: 'career',
    description: 'Targeted internship and junior engineer cover letter generator',
    route: '/student/cover-letter',
    status: 'available',
    featured: false,
    orderIndex: 7,
  },
  {
    id: 'study-planner',
    name: 'Exam & Study Planner',
    category: 'planning',
    description: 'Subject task breakdown and study session scheduler',
    route: '/student/study-planner',
    status: 'available',
    featured: false,
    orderIndex: 6,
  },
  {
    id: 'assignment-tracker',
    name: 'Assignment Tracker',
    category: 'organization',
    description: 'Deadline tracking with multi-criteria prioritization',
    route: '/student/assignments',
    status: 'available',
    featured: false,
    orderIndex: 7,
  },
  {
    id: 'timetable',
    name: 'College Timetable',
    category: 'planning',
    description: 'Weekly class schedule with O(N log N) overlap detection',
    route: '/student/timetable',
    status: 'available',
    featured: false,
    orderIndex: 8,
  },
  {
    id: 'certificates',
    name: 'Certificate Organizer',
    category: 'documents',
    description: 'Credential vault with duplicate detection and verification metadata',
    route: '/student/certificates',
    status: 'available',
    featured: false,
    orderIndex: 9,
  },
  {
    id: 'internships',
    name: 'Internship Tracker',
    category: 'opportunities',
    description: 'Application pipeline from Applied to Offer with stipend notes',
    route: '/student/internships',
    status: 'available',
    featured: false,
    orderIndex: 10,
  },
  {
    id: 'hackathons',
    name: 'Hackathon Tracker',
    category: 'opportunities',
    description: 'Hackathon timeline, repository links, and prize records',
    route: '/student/hackathons',
    status: 'available',
    featured: false,
    orderIndex: 11,
  },
  {
    id: 'exams',
    name: 'Exam Planner & Countdown',
    category: 'planning',
    description: 'Track internal CIE assessments and semester-end exams with dynamic countdowns',
    route: '/student/exams',
    status: 'available',
    featured: true,
    orderIndex: 12,
  },
  {
    id: 'tasks',
    name: 'Task Manager',
    category: 'planning',
    description: 'Daily coursework, lab preparation, and academic to-dos with priority tags',
    route: '/student/tasks',
    status: 'available',
    featured: false,
    orderIndex: 13,
  },
  {
    id: 'goals',
    name: 'Student Goal Tracker',
    category: 'planning',
    description: 'Milestones for SGPA targets, coding challenges, and career growth',
    route: '/student/goals',
    status: 'available',
    featured: false,
    orderIndex: 14,
  },
  {
    id: 'notifications',
    name: 'Smart Notifications',
    category: 'planning',
    description: 'Automated free email reminders and optional WhatsApp alerts for exams and study plans',
    route: '/student/settings/notifications',
    status: 'available',
    featured: false,
    orderIndex: 15,
  },
];
