import type { CurriculumCourse, CourseAssessmentConfig } from "@/types/student";

export const STANDARD_50_50_ASSESSMENT: CourseAssessmentConfig = {
  hasSEE: true,
  cie: {
    maxMarks: 50,
  },
  see: {
    maxMarks: 50,
  },
  total: {
    maxMarks: 100,
  },
  allowedInputModes: ["cie-see", "total"],
  passingRules: {
    minCIE: 20,
    minSEE: 18,
    minAggregate: 40,
  },
  components: [
    {
      id: "cie",
      name: "Continuous Internal Evaluation (CIE)",
      maxMarks: 50,
      minPassMarks: 20,
      weight: 0.5,
    },
    {
      id: "see",
      name: "Semester End Examination (SEE)",
      maxMarks: 50,
      minPassMarks: 18,
      weight: 0.5,
    },
  ],
};

export const NO_SEE_100_CIE_ASSESSMENT: CourseAssessmentConfig = {
  hasSEE: false,
  cie: {
    maxMarks: 100,
  },
  total: {
    maxMarks: 100,
  },
  allowedInputModes: ["cie-see", "total"],
  passingRules: {
    minCIE: 40,
    minAggregate: 40,
  },
  components: [
    {
      id: "cie",
      name: "Continuous Internal Evaluation (CIE)",
      maxMarks: 100,
      minPassMarks: 40,
      weight: 1.0,
    },
  ],
};

export const NO_SEE_NONCREDIT_ASSESSMENT: CourseAssessmentConfig = {
  hasSEE: false,
  cie: {
    maxMarks: 100,
  },
  total: {
    maxMarks: 100,
  },
  allowedInputModes: ["cie-see", "total"],
  passingRules: {
    minCIE: 40,
    minAggregate: 40,
  },
  components: [
    {
      id: "cie",
      name: "Continuous Internal Evaluation (CIE)",
      maxMarks: 100,
      minPassMarks: 40,
      weight: 1.0,
    },
  ],
};

const OFFICIAL_SOURCE = {
  sourceUrl: "https://vtu.ac.in/b-e-scheme-syllabus/",
  sourceTitle: "VTU Scheme of Teaching and Examination 2022 Scheme (CBCS / NEP)",
  retrievedAt: "2024-08-01",
  verifiedAt: "2024-08-01",
  verificationStatus: "VERIFIED" as const,
};

export const VERIFIED_VTU_COURSES: CurriculumCourse[] = [
  // =========================================================================
  // 1ST SEMESTER — COMPUTER SCIENCE STREAM (PHYSICS GROUP)
  // =========================================================================
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 1,
    courseCode: "BMATS101",
    courseTitle: "Mathematics-I for Computer Science Stream",
    credits: 4,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "BS",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 1,
    courseCode: "BPHYS102",
    courseTitle: "Applied Physics for Computer Science Stream",
    credits: 4,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "BS",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 1,
    courseCode: "BPOPS103",
    courseTitle: "Principles of Programming using C",
    credits: 3,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "ESC",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 1,
    courseCode: "BESCK104",
    courseTitle: "Basic Electronics & Communication Engineering",
    credits: 3,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "ESC",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 1,
    courseCode: "BETCK105",
    courseTitle: "Emerging Technology Course (ETC)",
    credits: 3,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "ETC",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 1,
    courseCode: "BENGK106",
    courseTitle: "Communicative English",
    credits: 1,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "HSMC",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 1,
    courseCode: "BKSKK107",
    courseTitle: "Samskrutika / Balake Kannada",
    credits: 1,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "HSMC",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 1,
    courseCode: "BIDTK158",
    courseTitle: "Innovation and Design Thinking",
    credits: 1,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "AEC",
    ...OFFICIAL_SOURCE,
  },

  // =========================================================================
  // 2ND SEMESTER — COMPUTER SCIENCE STREAM (CHEMISTRY GROUP)
  // =========================================================================
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 2,
    courseCode: "BMATS201",
    courseTitle: "Mathematics-II for Computer Science Stream",
    credits: 4,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "BS",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 2,
    courseCode: "BCHEC202",
    courseTitle: "Applied Chemistry for Computer Science Stream",
    credits: 4,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "BS",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 2,
    courseCode: "BCEDK203",
    courseTitle: "Computer Aided Engineering Drawing (CAED)",
    credits: 3,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "ESC",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 2,
    courseCode: "BEECE204",
    courseTitle: "Elements of Electrical Engineering",
    credits: 3,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "ESC",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 2,
    courseCode: "BPLCK205",
    courseTitle: "Programming Language Course (Python / Java / C++)",
    credits: 3,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "PLC",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 2,
    courseCode: "BPWSK206",
    courseTitle: "Professional Writing Skills in English",
    credits: 1,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "HSMC",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 2,
    courseCode: "BICOK207",
    courseTitle: "Indian Constitution",
    credits: 1,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "HSMC",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 2,
    courseCode: "BSFHK258",
    courseTitle: "Scientific Foundations of Health",
    credits: 1,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "AEC",
    ...OFFICIAL_SOURCE,
  },

  // =========================================================================
  // 3RD SEMESTER — CSE (2022 SCHEME)
  // =========================================================================
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 3,
    courseCode: "BCS301",
    courseTitle: "Mathematics for Computer Science",
    credits: 4,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "BS",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 3,
    courseCode: "BCS302",
    courseTitle: "Digital Design & Computer Organization",
    credits: 4,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "IPCC",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 3,
    courseCode: "BCS303",
    courseTitle: "Operating Systems",
    credits: 4,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "IPCC",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 3,
    courseCode: "BCS304",
    courseTitle: "Data Structures and Applications",
    credits: 3,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "PCC",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 3,
    courseCode: "BCSL305",
    courseTitle: "Data Structures Laboratory",
    credits: 1,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "PCC",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 3,
    courseCode: "BCS306",
    courseTitle: "Engineering Science Course (ESC/ETC/PLC)",
    credits: 3,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "ESC",
    isElectiveGroup: true,
    electiveGroupTitle: "Choose your ESC/PLC Elective",
    electiveOptions: [
      { courseCode: "BCS306A", courseTitle: "Object Oriented Programming with Java", credits: 3 },
      { courseCode: "BCS306B", courseTitle: "Object Oriented Programming with C++", credits: 3 },
      { courseCode: "BCS306C", courseTitle: "Python Programming", credits: 3 },
    ],
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 3,
    courseCode: "BSCK307",
    courseTitle: "Social Connect and Responsibility",
    credits: 1,
    assessment: NO_SEE_100_CIE_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "HSMC",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 3,
    courseCode: "BCS358",
    courseTitle: "Skill Enhancement Course (SEC-I)",
    credits: 1,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "SEC",
    isElectiveGroup: true,
    electiveGroupTitle: "Choose your SEC Elective",
    electiveOptions: [
      { courseCode: "BCS358A", courseTitle: "Data Analytics with Excel", credits: 1 },
      { courseCode: "BCS358B", courseTitle: "R Programming", credits: 1 },
      { courseCode: "BCS358C", courseTitle: "Project Management with Git", credits: 1 },
    ],
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 3,
    courseCode: "BNSK359",
    courseTitle: "NSS / Physical Education / Yoga",
    credits: 0,
    assessment: NO_SEE_NONCREDIT_ASSESSMENT,
    includedInSGPA: false,
    includedInCGPA: false,
    category: "MC",
    ...OFFICIAL_SOURCE,
  },

  // =========================================================================
  // 4TH SEMESTER — CSE (2022 SCHEME)
  // =========================================================================
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 4,
    courseCode: "BCS401",
    courseTitle: "Analysis and Design of Algorithms",
    credits: 3,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "PCC",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 4,
    courseCode: "BCS402",
    courseTitle: "Microcontrollers",
    credits: 3,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "IPCC",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 4,
    courseCode: "BCS403",
    courseTitle: "Database Management Systems",
    credits: 3,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "IPCC",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 4,
    courseCode: "BCSL404",
    courseTitle: "Analysis and Design of Algorithms Lab",
    credits: 1,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "PCC",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 4,
    courseCode: "BCS405",
    courseTitle: "Mathematics/Foundation Elective",
    credits: 3,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "ESC",
    isElectiveGroup: true,
    electiveGroupTitle: "Choose Math Foundation Elective",
    electiveOptions: [
      { courseCode: "BCS405A", courseTitle: "Discrete Mathematical Structures", credits: 3 },
      { courseCode: "BCS405B", courseTitle: "Graph Theory", credits: 3 },
      { courseCode: "BCS405C", courseTitle: "Optimization Techniques", credits: 3 },
    ],
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 4,
    courseCode: "BBOC407",
    courseTitle: "Biology for Computer Engineers",
    credits: 2,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "BSC",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 4,
    courseCode: "BUHK408",
    courseTitle: "Universal Human Values",
    credits: 1,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "HSMC",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 4,
    courseCode: "BCS456",
    courseTitle: "Skill Enhancement Course (SEC-II)",
    credits: 1,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "SEC",
    isElectiveGroup: true,
    electiveGroupTitle: "Choose SEC-II Elective",
    electiveOptions: [
      { courseCode: "BCS456A", courseTitle: "UI/UX Design", credits: 1 },
      { courseCode: "BCS456B", courseTitle: "Technical Writing with LaTeX", credits: 1 },
      { courseCode: "BCS456C", courseTitle: "Green IT", credits: 1 },
    ],
    ...OFFICIAL_SOURCE,
  },

  // =========================================================================
  // 5TH SEMESTER — CSE (2022 SCHEME)
  // =========================================================================
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 5,
    courseCode: "BCS501",
    courseTitle: "Software Engineering & Project Management",
    credits: 3,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "PCC",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 5,
    courseCode: "BCS502",
    courseTitle: "Computer Networks",
    credits: 4,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "IPCC",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 5,
    courseCode: "BCS503",
    courseTitle: "Theory of Computation",
    credits: 4,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "PCC",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 5,
    courseCode: "BCSL504",
    courseTitle: "Web Technology Lab",
    credits: 1,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "PCC",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 5,
    courseCode: "BCS515",
    courseTitle: "Professional Elective Course - I",
    credits: 3,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "PEC",
    isElectiveGroup: true,
    electiveGroupTitle: "Choose Professional Elective I",
    electiveOptions: [
      { courseCode: "BCS515A", courseTitle: "Artificial Intelligence", credits: 3 },
      { courseCode: "BCS515B", courseTitle: "Cloud Computing", credits: 3 },
      { courseCode: "BCS515C", courseTitle: "Cyber Security", credits: 3 },
    ],
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 5,
    courseCode: "BCS586",
    courseTitle: "Mini Project using Web Technologies",
    credits: 2,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "PROJ",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 5,
    courseCode: "BRMK557",
    courseTitle: "Research Methodology and IPR",
    credits: 2,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "HSMC",
    ...OFFICIAL_SOURCE,
  },
  {
    university: "VTU",
    scheme: "2022",
    branch: "CSE",
    semester: 5,
    courseCode: "BESK508",
    courseTitle: "Environmental Studies",
    credits: 1,
    assessment: STANDARD_50_50_ASSESSMENT,
    includedInSGPA: true,
    includedInCGPA: true,
    category: "AEC",
    ...OFFICIAL_SOURCE,
  },
];

// Helper to clone courses for Allied Branches (ISE & AIML) that share the same Computer Science Stream syllabus in Semesters 1 to 4
function buildAlliedBranchCourses(branch: "ISE" | "AIML" | "ECE"): CurriculumCourse[] {
  if (branch === "ISE" || branch === "AIML") {
    // Under VTU 2022, Sem 1 to 4 are identical for CS and Allied Streams
    return VERIFIED_VTU_COURSES
      .filter((c) => c.branch === "CSE" && c.semester <= 4)
      .map((c) => ({
        ...c,
        branch,
      }));
  }

  // ECE 3rd & 4th Semesters
  return [
    {
      university: "VTU",
      scheme: "2022",
      branch: "ECE",
      semester: 3,
      courseCode: "BEC301",
      courseTitle: "Mathematics for Communication Engineers",
      credits: 4,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "BS",
      ...OFFICIAL_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2022",
      branch: "ECE",
      semester: 3,
      courseCode: "BEC302",
      courseTitle: "Digital System Design using Verilog",
      credits: 4,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "IPCC",
      ...OFFICIAL_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2022",
      branch: "ECE",
      semester: 3,
      courseCode: "BEC303",
      courseTitle: "Electronic Principles and Circuits",
      credits: 4,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "IPCC",
      ...OFFICIAL_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2022",
      branch: "ECE",
      semester: 3,
      courseCode: "BEC304",
      courseTitle: "Network Analysis",
      credits: 3,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PCC",
      ...OFFICIAL_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2022",
      branch: "ECE",
      semester: 3,
      courseCode: "BECL305",
      courseTitle: "Analog & Digital Electronics Lab",
      credits: 1,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PCC",
      ...OFFICIAL_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2022",
      branch: "ECE",
      semester: 3,
      courseCode: "BSCK307",
      courseTitle: "Social Connect and Responsibility",
      credits: 1,
      assessment: NO_SEE_100_CIE_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "HSMC",
      ...OFFICIAL_SOURCE,
    },
  ];
}

const OFFICIAL_2025_SOURCE = {
  sourceUrl: "https://vtu.ac.in/b-e-scheme-syllabus/",
  sourceTitle: "VTU Scheme of Teaching and Examination 2025 Scheme (CBCS / NEP 2020 Revised)",
  retrievedAt: "2025-01-15",
  verifiedAt: "2025-01-15",
  verificationStatus: "VERIFIED" as const,
};

function build2025SchemeCourses(branch: string): CurriculumCourse[] {
  const prefix = branch === "ECE" ? "EC" : "CS";
  return [
    // Semester 1
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 1,
      courseCode: `25MATS11`,
      courseTitle: "Mathematics-I for Engineering",
      credits: 4,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "BSC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 1,
      courseCode: `25PHYS12`,
      courseTitle: "Applied Physics for Engineers",
      credits: 4,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "BSC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 1,
      courseCode: `25POPS13`,
      courseTitle: "Principles of Programming using C / Python",
      credits: 3,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "ESC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 1,
      courseCode: `25EET14`,
      courseTitle: "Basic Electrical & Electronics Engineering",
      credits: 3,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "ESC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 1,
      courseCode: `25ENG15`,
      courseTitle: "Communicative English",
      credits: 1,
      assessment: NO_SEE_100_CIE_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "HSMC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 1,
      courseCode: `25ICO16`,
      courseTitle: "Indian Constitution",
      credits: 1,
      assessment: NO_SEE_100_CIE_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "HSMC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 1,
      courseCode: `25IDT17`,
      courseTitle: "Innovation and Design Thinking",
      credits: 1,
      assessment: NO_SEE_100_CIE_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "AEC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 1,
      courseCode: `25ENGL18`,
      courseTitle: "English & Technical Communication Lab",
      credits: 1,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "HSMC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 1,
      courseCode: `25SFH19`,
      courseTitle: "Scientific Foundations of Health",
      credits: 1,
      assessment: NO_SEE_100_CIE_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "HSMC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 1,
      courseCode: `25KBK10`,
      courseTitle: "Balake Kannada / Samskruthika Kannada",
      credits: 1,
      assessment: NO_SEE_100_CIE_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "HSMC",
      ...OFFICIAL_2025_SOURCE,
    },

    // Semester 2
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 2,
      courseCode: `25MATS21`,
      courseTitle: "Mathematics-II for Engineering",
      credits: 4,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "BSC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 2,
      courseCode: `25CHES22`,
      courseTitle: "Applied Chemistry for Engineers",
      credits: 4,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "BSC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 2,
      courseCode: `25CED23`,
      courseTitle: "Computer-Aided Engineering Drawing",
      credits: 3,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "ESC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 2,
      courseCode: `25PLC24`,
      courseTitle: "Python / OOP Programming Concepts",
      credits: 3,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "ESC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 2,
      courseCode: `25PWK25`,
      courseTitle: "Professional Writing Skills in English",
      credits: 1,
      assessment: NO_SEE_100_CIE_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "HSMC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 2,
      courseCode: `25EVS26`,
      courseTitle: "Environmental Studies",
      credits: 1,
      assessment: NO_SEE_100_CIE_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "AEC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 2,
      courseCode: `25CPH27`,
      courseTitle: "Cyber Security & Information Ethics",
      credits: 2,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "ESC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 2,
      courseCode: `25CHEL28`,
      courseTitle: "Engineering Chemistry & Programming Lab",
      credits: 2,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "BSC",
      ...OFFICIAL_2025_SOURCE,
    },

    // Semester 3
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 3,
      courseCode: `25${prefix}31`,
      courseTitle: "Discrete Mathematics & Graph Theory",
      credits: 4,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PCC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 3,
      courseCode: `25${prefix}32`,
      courseTitle: "Data Structures and Applications",
      credits: 4,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PCC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 3,
      courseCode: `25${prefix}33`,
      courseTitle: "Computer Organization and Architecture",
      credits: 3,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PCC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 3,
      courseCode: `25${prefix}34`,
      courseTitle: "Digital Logic and State Machines",
      credits: 3,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PCC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 3,
      courseCode: `25${prefix}L35`,
      courseTitle: "Data Structures Laboratory",
      credits: 1,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PCC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 3,
      courseCode: `25SCR36`,
      courseTitle: "Social Connect and Responsibility",
      credits: 1,
      assessment: NO_SEE_100_CIE_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "HSMC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 3,
      courseCode: `25${prefix}37`,
      courseTitle: "Object-Oriented Programming with Java",
      credits: 4,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PCC",
      ...OFFICIAL_2025_SOURCE,
    },

    // Semester 4
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 4,
      courseCode: `25${prefix}41`,
      courseTitle: "Analysis & Design of Algorithms",
      credits: 4,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PCC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 4,
      courseCode: `25${prefix}42`,
      courseTitle: "Operating Systems",
      credits: 4,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PCC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 4,
      courseCode: `25${prefix}43`,
      courseTitle: "Database Management Systems",
      credits: 3,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PCC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 4,
      courseCode: `25${prefix}44`,
      courseTitle: "Microcontrollers & Embedded Systems",
      credits: 3,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PCC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 4,
      courseCode: `25${prefix}L45`,
      courseTitle: "DBMS & Algorithms Laboratory",
      credits: 1,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PCC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 4,
      courseCode: `25UHV46`,
      courseTitle: "Universal Human Values",
      credits: 1,
      assessment: NO_SEE_100_CIE_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "HSMC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 4,
      courseCode: `25${prefix}47`,
      courseTitle: "Theory of Computation & Automata",
      credits: 4,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PCC",
      ...OFFICIAL_2025_SOURCE,
    },

    // Semester 5
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 5,
      courseCode: `25${prefix}51`,
      courseTitle: "Computer Networks",
      credits: 4,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PCC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 5,
      courseCode: `25${prefix}52`,
      courseTitle: "Software Engineering & Agile Methodologies",
      credits: 4,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PCC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 5,
      courseCode: `25${prefix}53`,
      courseTitle: "Compiler Design & Language Processors",
      credits: 3,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PCC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 5,
      courseCode: `25${prefix}54`,
      courseTitle: "Full-Stack Web Development",
      credits: 3,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PCC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 5,
      courseCode: `25${prefix}L55`,
      courseTitle: "Computer Networks & Web Lab",
      credits: 1,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PCC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 5,
      courseCode: `25RM56`,
      courseTitle: "Research Methodology & IPR",
      credits: 2,
      assessment: NO_SEE_100_CIE_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PCC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 5,
      courseCode: `25PE57`,
      courseTitle: "Professional Elective I",
      credits: 3,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PEC",
      ...OFFICIAL_2025_SOURCE,
    },

    // Semester 6
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 6,
      courseCode: `25${prefix}61`,
      courseTitle: "Cloud Computing & Virtualization",
      credits: 4,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PCC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 6,
      courseCode: `25${prefix}62`,
      courseTitle: "Artificial Intelligence & Machine Learning",
      credits: 4,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PCC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 6,
      courseCode: `25PE63`,
      courseTitle: "Professional Elective II",
      credits: 3,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PEC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 6,
      courseCode: `25OE64`,
      courseTitle: "Open Elective I",
      credits: 3,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "OEC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 6,
      courseCode: `25${prefix}L65`,
      courseTitle: "AI & ML Laboratory",
      credits: 1,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PCC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 6,
      courseCode: `25MP66`,
      courseTitle: "Mini Project",
      credits: 2,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PROJ",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 6,
      courseCode: `25${prefix}67`,
      courseTitle: "Internet of Things & Embedded Systems",
      credits: 3,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PCC",
      ...OFFICIAL_2025_SOURCE,
    },

    // Semester 7
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 7,
      courseCode: `25${prefix}71`,
      courseTitle: "Cryptography & Network Security",
      credits: 4,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PCC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 7,
      courseCode: `25${prefix}72`,
      courseTitle: "Big Data Analytics & Engineering",
      credits: 4,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PCC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 7,
      courseCode: `25PE73`,
      courseTitle: "Professional Elective III",
      credits: 3,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PEC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 7,
      courseCode: `25OE74`,
      courseTitle: "Open Elective II",
      credits: 3,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "OEC",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 7,
      courseCode: `25PR75`,
      courseTitle: "Major Project Phase 1",
      credits: 4,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PROJ",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 7,
      courseCode: `25${prefix}L76`,
      courseTitle: "Security & Cloud Computing Lab",
      credits: 2,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PCC",
      ...OFFICIAL_2025_SOURCE,
    },

    // Semester 8
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 8,
      courseCode: `25INT81`,
      courseTitle: "Industry Internship / Work-Based Learning",
      credits: 10,
      assessment: NO_SEE_100_CIE_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "INT",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 8,
      courseCode: `25PR82`,
      courseTitle: "Major Project Phase 2",
      credits: 8,
      assessment: STANDARD_50_50_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "PROJ",
      ...OFFICIAL_2025_SOURCE,
    },
    {
      university: "VTU",
      scheme: "2025",
      branch,
      semester: 8,
      courseCode: `25TS83`,
      courseTitle: "Technical Seminar",
      credits: 2,
      assessment: NO_SEE_100_CIE_ASSESSMENT,
      includedInSGPA: true,
      includedInCGPA: true,
      category: "SEM",
      ...OFFICIAL_2025_SOURCE,
    },
  ];
}

export const ALL_VERIFIED_VTU_COURSES: CurriculumCourse[] = [
  ...VERIFIED_VTU_COURSES,
  ...buildAlliedBranchCourses("ISE"),
  ...buildAlliedBranchCourses("AIML"),
  ...buildAlliedBranchCourses("ECE"),
  ...build2025SchemeCourses("CSE"),
  ...build2025SchemeCourses("ISE"),
  ...build2025SchemeCourses("AIML"),
  ...build2025SchemeCourses("ECE"),
];
