import {
  InterviewQuestion,
  InterviewSession,
  InterviewMode,
  InterviewCompany,
  InterviewTurnResponse,
  ProctoringViolationEvent,
  InterviewSettings,
} from "@/types/interview";
import { isSupabaseConfigured } from "@/lib/supabase/config";
import { createClient } from "@/lib/supabase/client";

export const DEFAULT_INTERVIEW_SETTINGS: InterviewSettings = {
  defaultMcqTimeLimitSeconds: 60,
  defaultVideoTimeLimitSeconds: 120,
  maxProctoringWarnings: 4,
  enableCameraDeviceCheck: true,
  enableAiTtsFallback: true,
};

export const SEEDED_QUESTIONS: InterviewQuestion[] = [
  // --- GOOGLE ---
  {
    id: "q_goog_1",
    role: "Software Engineer",
    type: "mcq",
    difficulty: "Medium",
    company: "Google",
    question: "In Two Sum (finding two indices that sum to a target), what is the optimal time and space complexity using a hash map?",
    options: [
      "O(N^2) Time, O(1) Space",
      "O(N log N) Time, O(1) Space",
      "O(N) Time, O(N) Space",
      "O(1) Time, O(N) Space",
    ],
    correctAnswer: 2,
    explanation: "By hashing each element in a single pass, complement lookup takes O(1) on average, yielding O(N) time and O(N) auxiliary space.",
    rubric: {
      criteria: ["Complexity analysis", "Hash map collision consideration"],
      sampleStrongAnswer: "Single-pass hash table gives O(N) time and O(N) space.",
    },
    timeLimitSeconds: 60,
    exposureCount: 0,
  },
  {
    id: "q_goog_2",
    role: "Software Engineer",
    type: "system_design",
    difficulty: "Hard",
    company: "Google",
    question: "Design a high-scale URL shortener (e.g. TinyURL) handling 10,000 writes/sec. How do you ensure unique, short, non-guessable hash keys?",
    options: undefined,
    explanation: "Use Base62 encoding on auto-incrementing 64-bit IDs generated by a distributed ID generator (e.g. Snowflake) or MD5/SHA-256 with collision resolution.",
    rubric: {
      criteria: [
        "Base62 encoding explanation",
        "Distributed ID generation",
        "Cache layer (Redis)",
        "Database sharding",
      ],
      sampleStrongAnswer: "I would use a distributed ID generator like Snowflake to generate a unique 64-bit integer, encode it into Base62 for a 7-character key, store it in a distributed NoSQL store, and front reads with a Redis cache cluster.",
    },
    timeLimitSeconds: 180,
    exposureCount: 0,
  },

  // --- MICROSOFT ---
  {
    id: "q_msft_1",
    role: "Backend Engineer",
    type: "mcq",
    difficulty: "Medium",
    company: "Microsoft",
    question: "Which isolation level in SQL prevents 'Dirty Reads', 'Non-repeatable Reads', and 'Phantom Reads'?",
    options: [
      "Read Committed",
      "Repeatable Read",
      "Serializable",
      "Read Uncommitted",
    ],
    correctAnswer: 2,
    explanation: "Serializable is the highest isolation level. It prevents dirty reads, non-repeatable reads, and phantom reads by enforcing serial execution order.",
    rubric: {
      criteria: ["ACID isolation levels knowledge", "Transaction locking understanding"],
      sampleStrongAnswer: "Serializable prevents all three anomalies by locking the relevant key ranges or snapshot serialization.",
    },
    timeLimitSeconds: 60,
    exposureCount: 0,
  },
  {
    id: "q_msft_2",
    role: "Software Engineer",
    type: "behavioral",
    difficulty: "Medium",
    company: "Microsoft",
    question: "Describe a situation where you had a strong technical disagreement with a colleague or lead. How did you resolve it?",
    options: undefined,
    explanation: "Evaluates emotional intelligence, data-driven reasoning, respect for consensus, and commitment to project success.",
    rubric: {
      criteria: [
        "STAR framework structure",
        "Data-driven argumentation or benchmarking",
        "Constructive collaboration",
        "Clear measurable outcome",
      ],
      sampleStrongAnswer: "In my previous project, we disagreed on whether to use REST or gRPC for internal service communication. I proposed a timed spike benchmark comparing latency and serialization overhead. The benchmark showed a 3x speedup with gRPC for high-throughput nodes, so we aligned on adopting gRPC for core services while keeping REST for public gateways.",
    },
    timeLimitSeconds: 120,
    exposureCount: 0,
  },

  // --- AMAZON ---
  {
    id: "q_amzn_1",
    role: "Software Engineer",
    type: "mcq",
    difficulty: "Medium",
    company: "Amazon",
    question: "To implement an LRU (Least Recently Used) Cache with strict O(1) get and O(1) put operations, which pair of data structures is required?",
    options: [
      "Array and Binary Search Tree",
      "Doubly Linked List and Hash Map",
      "Singly Linked List and Min-Heap",
      "Stack and Queue",
    ],
    correctAnswer: 1,
    explanation: "A Hash Map provides O(1) lookup of node pointers, while a Doubly Linked List allows O(1) removal and insertion at head/tail to maintain recency.",
    rubric: {
      criteria: ["Node eviction logic", "Pointer manipulation understanding"],
      sampleStrongAnswer: "Hash map maps keys to doubly linked list nodes for O(1) access and re-ordering.",
    },
    timeLimitSeconds: 60,
    exposureCount: 0,
  },
  {
    id: "q_amzn_2",
    role: "Software Engineer",
    type: "behavioral",
    difficulty: "Medium",
    company: "Amazon",
    question: "Amazon Leadership Principle: 'Bias for Action'. Give an example of a time when you had to make a calculated decision without complete information or consensus.",
    options: undefined,
    explanation: "Tests the candidate's speed of decision making, calculated risk tolerance, and ability to reverse decisions if needed.",
    rubric: {
      criteria: [
        "Clear problem context with missing data",
        "Risk mitigation steps taken",
        "Fast execution and feedback loop",
        "Key retrospective learning",
      ],
      sampleStrongAnswer: "During a critical release before campus placement week, our authentication provider experienced intermittent timeout spikes. Without waiting for a 24-hour vendor ticket response, I implemented a circuit breaker with exponential backoff and a local session cache fallback. This prevented 500+ student sign-in drops.",
    },
    timeLimitSeconds: 120,
    exposureCount: 0,
  },

  // --- INFOSYS ---
  {
    id: "q_infy_1",
    role: "Software Engineer",
    type: "mcq",
    difficulty: "Easy",
    company: "Infosys",
    question: "In Object-Oriented Programming, what constitutes method overloading?",
    options: [
      "Same method name, different signatures within the same class",
      "Same method name and same signature in a child class overriding parent",
      "A method that accepts any number of dynamic arguments",
      "A private method inherited across packages",
    ],
    correctAnswer: 0,
    explanation: "Method overloading occurs at compile time when methods in the same class share a name but differ in parameter count, type, or order.",
    rubric: {
      criteria: ["Static polymorphism understanding", "Compile-time vs runtime binding"],
      sampleStrongAnswer: "Overloading is compile-time polymorphism where methods have identical names but different argument lists in the same class.",
    },
    timeLimitSeconds: 60,
    exposureCount: 0,
  },
  {
    id: "q_infy_2",
    role: "Software Engineer",
    type: "technical_coding",
    difficulty: "Medium",
    company: "Infosys",
    question: "Explain the ACID properties of database transactions. How does the 'Atomicity' property protect a fund transfer between two bank accounts?",
    options: undefined,
    explanation: "Atomicity ensures all operations succeed or all are rolled back. In a transfer, debiting account A and crediting account B must happen completely or not at all.",
    rubric: {
      criteria: [
        "Clear definitions of Atomicity, Consistency, Isolation, Durability",
        "Bank transfer failure scenario (e.g. power loss after debit)",
        "Rollback mechanism using transaction logs",
      ],
      sampleStrongAnswer: "Atomicity guarantees the 'all-or-nothing' principle. In a fund transfer, if $500 is debited from Account A but the system crashes before crediting Account B, the transaction rollback ensures Account A retains its balance.",
    },
    timeLimitSeconds: 120,
    exposureCount: 0,
  },

  // --- TCS ---
  {
    id: "q_tcs_1",
    role: "Software Engineer",
    type: "mcq",
    difficulty: "Easy",
    company: "TCS",
    question: "Which of the following statements correctly distinguishes TCP from UDP?",
    options: [
      "TCP is connectionless and faster, while UDP is connection-oriented with acknowledgments",
      "TCP provides guaranteed in-order delivery via 3-way handshakes; UDP is connectionless with lower latency",
      "UDP operates on the Network Layer; TCP operates on the Transport Layer",
      "TCP can only transmit text; UDP transmits binary multimedia packets",
    ],
    correctAnswer: 1,
    explanation: "TCP is connection-oriented, providing sequencing, flow control, and retransmission. UDP is lightweight and connectionless, ideal for video streaming and gaming.",
    rubric: {
      criteria: ["Transport layer protocols", "Connection handshake vs packet streaming"],
      sampleStrongAnswer: "TCP guarantees delivery and order using handshakes and ACKs; UDP trades reliability for low overhead and speed.",
    },
    timeLimitSeconds: 60,
    exposureCount: 0,
  },
  {
    id: "q_tcs_2",
    role: "Software Engineer",
    type: "behavioral",
    difficulty: "Easy",
    company: "TCS",
    question: "Tell me about yourself, your academic background, and why you are interested in starting your engineering career with our company.",
    options: undefined,
    explanation: "Evaluates communication clarity, professional alignment, enthusiasm, and summary skills.",
    rubric: {
      criteria: [
        "Structured overview: Education, key technical skills, projects",
        "Specific alignment with company values or engineering focus",
        "Professional tone and confidence",
      ],
      sampleStrongAnswer: "I am a computer science engineering student passionate about scalable web architecture and distributed systems. Throughout my coursework and projects, I built full-stack applications and practiced data structures extensively. I want to join TCS because of its massive enterprise digital transformation footprint and continuous learning culture.",
    },
    timeLimitSeconds: 120,
    exposureCount: 0,
  },

  // --- WIPRO ---
  {
    id: "q_wipro_1",
    role: "Software Engineer",
    type: "mcq",
    difficulty: "Easy",
    company: "Wipro",
    question: "In Relational Database Normalization, what is the prerequisite for a relation to be in Third Normal Form (3NF)?",
    options: [
      "It must be in 1NF and have no duplicate rows",
      "It must be in 2NF and have no transitive functional dependencies",
      "All columns must have composite primary keys",
      "It must contain no foreign keys",
    ],
    correctAnswer: 1,
    explanation: "3NF requires the table to be in 2NF, and every non-prime attribute must be non-transitively dependent on every candidate key.",
    rubric: {
      criteria: ["Database normalization rules", "Transitive dependency definition"],
      sampleStrongAnswer: "A table is in 3NF if it is in 2NF and no non-key attribute depends transitively on the primary key.",
    },
    timeLimitSeconds: 60,
    exposureCount: 0,
  },

  // --- ACCENTURE ---
  {
    id: "q_acn_1",
    role: "Software Engineer",
    type: "mcq",
    difficulty: "Easy",
    company: "Accenture",
    question: "In Cloud Computing architectures, which service model provides the consumer with virtual servers, storage, and networking without managing hardware?",
    options: [
      "SaaS (Software as a Service)",
      "PaaS (Platform as a Service)",
      "IaaS (Infrastructure as a Service)",
      "FaaS (Function as a Service)",
    ],
    correctAnswer: 2,
    explanation: "IaaS (e.g. AWS EC2, Azure VMs, Google Compute Engine) provisions virtualized compute, storage, and networking resources.",
    rubric: {
      criteria: ["Cloud computing service models", "Infrastructure vs Platform differentiation"],
      sampleStrongAnswer: "IaaS provides raw virtualized hardware resources such as VMs and block storage.",
    },
    timeLimitSeconds: 60,
    exposureCount: 0,
  },
];

class InterviewService {
  private localQuestions: InterviewQuestion[] = [...SEEDED_QUESTIONS];
  private localSessions: Map<string, InterviewSession> = new Map();
  private localSettings: InterviewSettings = { ...DEFAULT_INTERVIEW_SETTINGS };

  /**
   * Returns available questions matching role and company filters, rotated by exposure count.
   */
  public async getQuestions(options?: {
    role?: string;
    company?: InterviewCompany;
    mode?: InterviewMode;
    count?: number;
  }): Promise<InterviewQuestion[]> {
    const targetCount = options?.count || 5;
    let pool = [...this.localQuestions];

    if (options?.company && options.company !== "General") {
      const companyMatches = pool.filter((q) => q.company === options.company);
      if (companyMatches.length > 0) {
        pool = companyMatches;
      }
    }

    if (options?.mode === "text_mcq") {
      const mcqOnly = pool.filter((q) => q.type === "mcq");
      if (mcqOnly.length >= targetCount) {
        pool = mcqOnly;
      }
    }

    // Deterministic rotation: Sort by lowest exposure count, then shuffle tie-breaks
    pool.sort((a, b) => a.exposureCount - b.exposureCount);
    const selected = pool.slice(0, targetCount);

    // Increment exposure count
    for (const q of selected) {
      q.exposureCount += 1;
    }

    return selected;
  }

  /**
   * Starts a new Mock Interview 2.0 session.
   */
  public async createSession(params: {
    userId: string;
    mode: InterviewMode;
    role: string;
    company?: InterviewCompany;
    questionCount?: number;
  }): Promise<InterviewSession> {
    const questions = await this.getQuestions({
      role: params.role,
      company: params.company,
      mode: params.mode,
      count: params.questionCount || (params.mode === "text_mcq" ? 5 : 4),
    });

    const session: InterviewSession = {
      id: `session_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`,
      userId: params.userId || "guest",
      mode: params.mode,
      role: params.role,
      targetCompany: params.company,
      questions,
      responses: [],
      currentQuestionIndex: 0,
      overallScore: 0,
      proctoringViolations: [],
      status: "in_progress",
      startedAt: new Date().toISOString(),
    };

    this.localSessions.set(session.id, session);

    // Persist to Supabase if available
    if (isSupabaseConfigured()) {
      try {
        const supabase = createClient();
        await supabase.from("interview_sessions").insert({
          id: session.id,
          user_id: session.userId,
          mode: session.mode,
          role: session.role,
          company: session.targetCompany,
          questions: session.questions,
          responses: session.responses,
          overall_score: session.overallScore,
          proctoring_violations: session.proctoringViolations,
          status: session.status,
          started_at: session.startedAt,
        });
      } catch (err) {
        console.warn("[InterviewService] Supabase session sync failed, using local storage:", err);
      }
    }

    return session;
  }

  /**
   * Retrieves a session by ID.
   */
  public async getSession(sessionId: string): Promise<InterviewSession | null> {
    const local = this.localSessions.get(sessionId);
    if (local) return local;

    if (isSupabaseConfigured()) {
      try {
        const supabase = createClient();
        const { data } = await supabase
          .from("interview_sessions")
          .select("*")
          .eq("id", sessionId)
          .single();

        if (data) {
          const session: InterviewSession = {
            id: data.id,
            userId: data.user_id,
            mode: data.mode,
            role: data.role,
            targetCompany: data.company,
            questions: data.questions || [],
            responses: data.responses || [],
            currentQuestionIndex: data.responses ? data.responses.length : 0,
            overallScore: Number(data.overall_score || 0),
            proctoringViolations: data.proctoring_violations || [],
            status: data.status,
            startedAt: data.started_at,
            completedAt: data.completed_at,
          };
          this.localSessions.set(session.id, session);
          return session;
        }
      } catch {
        return null;
      }
    }

    return null;
  }

  /**
   * Submits a response for the current question in a session.
   */
  public async submitResponse(params: {
    sessionId: string;
    questionId: string;
    userAnswer: string | number;
    timeSpentSeconds: number;
  }): Promise<{ session: InterviewSession; response: InterviewTurnResponse }> {
    const session = await this.getSession(params.sessionId);
    if (!session) {
      throw new Error(`Interview session not found: ${params.sessionId}`);
    }

    if (session.status !== "in_progress") {
      throw new Error(`Cannot submit response to session with status: ${session.status}`);
    }

    const question = session.questions.find((q) => q.id === params.questionId);
    if (!question) {
      throw new Error(`Question ${params.questionId} not part of this session.`);
    }

    let isCorrect: boolean | undefined = undefined;
    let score = 70; // baseline for open-ended answers
    let feedback: InterviewTurnResponse["feedback"] = {
      rating: "Strong",
      notes: "Answer recorded successfully.",
      tips: ["Structure responses clearly with real-world examples."],
    };

    if (question.type === "mcq") {
      const selectedIndex = Number(params.userAnswer);
      isCorrect = selectedIndex === question.correctAnswer;
      score = isCorrect ? 100 : 0;
      feedback = {
        rating: isCorrect ? "Excellent" : "Incorrect",
        notes: isCorrect
          ? `Correct! ${question.explanation || ""}`
          : `Incorrect. The correct answer was: ${
              question.options ? question.options[question.correctAnswer ?? 0] : ""
            }. ${question.explanation || ""}`,
        tips: isCorrect
          ? ["Great accuracy under timed test conditions."]
          : ["Review core theory and time management."],
      };
    } else {
      // Freeform or Behavioral answer evaluation
      const answerStr = String(params.userAnswer).trim();
      const wordCount = answerStr.split(/\s+/).length;

      if (wordCount < 15) {
        score = 45;
        feedback = {
          rating: "Needs improvement",
          notes: "Your answer was very brief. Elaborate with specific details and context.",
          tips: ["Use the STAR method (Situation, Task, Action, Result)."],
        };
      } else if (wordCount > 150) {
        score = 88;
        feedback = {
          rating: "Strong",
          notes: "Comprehensive and structured response demonstrating clear technical competence.",
          tips: ["Keep responses punchy and highlight quantifiable results."],
        };
      } else {
        score = 78;
        feedback = {
          rating: "Strong",
          notes: "Solid answer addressing the core question prompt.",
          tips: ["Consider discussing trade-offs and alternative solutions."],
        };
      }
    }

    const turnResponse: InterviewTurnResponse = {
      questionId: params.questionId,
      userAnswer: params.userAnswer,
      timeSpentSeconds: params.timeSpentSeconds,
      isCorrect,
      score,
      feedback,
      submittedAt: new Date().toISOString(),
    };

    session.responses.push(turnResponse);
    session.currentQuestionIndex = session.responses.length;

    // Check if session is finished
    if (session.responses.length >= session.questions.length) {
      session.status = "completed";
      session.completedAt = new Date().toISOString();
      // Calculate overall score (average of turns)
      const total = session.responses.reduce((sum, r) => sum + (r.score || 0), 0);
      session.overallScore = Math.round(total / session.responses.length);
    }

    this.localSessions.set(session.id, session);
    this.syncSession(session);

    return { session, response: turnResponse };
  }

  /**
   * Records a proctoring violation (tab switch, window blur, or fullscreen exit).
   * Progressive enforcement: triggers termination if violations exceed max warnings.
   */
  public async recordProctoringViolation(params: {
    sessionId: string;
    type: ProctoringViolationEvent["type"];
  }): Promise<{ session: InterviewSession; terminated: boolean; warningCount: number }> {
    const session = await this.getSession(params.sessionId);
    if (!session) {
      throw new Error(`Interview session not found: ${params.sessionId}`);
    }

    const warningCount = session.proctoringViolations.length + 1;
    const violation: ProctoringViolationEvent = {
      id: `viol_${Date.now()}`,
      type: params.type,
      timestamp: new Date().toISOString(),
      warningNumber: warningCount,
    };

    session.proctoringViolations.push(violation);

    let terminated = false;
    if (warningCount >= this.localSettings.maxProctoringWarnings) {
      session.status = "terminated_proctoring";
      session.completedAt = new Date().toISOString();
      session.overallScore = Math.min(session.overallScore, 40); // penalty on termination
      terminated = true;
    }

    this.localSessions.set(session.id, session);
    this.syncSession(session);

    return { session, terminated, warningCount };
  }

  /**
   * Adds or updates a question in the question bank.
   */
  public async upsertQuestion(question: InterviewQuestion): Promise<InterviewQuestion> {
    const idx = this.localQuestions.findIndex((q) => q.id === question.id);
    if (idx >= 0) {
      this.localQuestions[idx] = question;
    } else {
      this.localQuestions.push(question);
    }

    if (isSupabaseConfigured()) {
      try {
        const supabase = createClient();
        await supabase.from("interview_questions").upsert({
          id: question.id,
          role: question.role,
          type: question.type,
          difficulty: question.difficulty,
          company: question.company,
          question: question.question,
          options: question.options,
          correct_answer: question.correctAnswer,
          explanation: question.explanation,
          rubric: question.rubric,
          time_limit_seconds: question.timeLimitSeconds,
          exposure_count: question.exposureCount,
        });
      } catch (err) {
        console.warn("[InterviewService] Question upsert sync to Supabase failed:", err);
      }
    }

    return question;
  }

  /**
   * Gets current interview settings.
   */
  public getSettings(): InterviewSettings {
    return { ...this.localSettings };
  }

  /**
   * Updates interview settings.
   */
  public updateSettings(newSettings: Partial<InterviewSettings>): InterviewSettings {
    this.localSettings = { ...this.localSettings, ...newSettings };
    return { ...this.localSettings };
  }

  /**
   * Synchronizes session state to Supabase.
   */
  private async syncSession(session: InterviewSession): Promise<void> {
    if (!isSupabaseConfigured()) return;
    try {
      const supabase = createClient();
      await supabase.from("interview_sessions").upsert({
        id: session.id,
        user_id: session.userId,
        mode: session.mode,
        role: session.role,
        company: session.targetCompany,
        questions: session.questions,
        responses: session.responses,
        overall_score: session.overallScore,
        proctoring_violations: session.proctoringViolations,
        status: session.status,
        started_at: session.startedAt,
        completed_at: session.completedAt,
      });
    } catch (err) {
      console.warn("[InterviewService] Session sync failed:", err);
    }
  }
}

export const interviewService = new InterviewService();
