import {
  InterviewQuestion,
  InterviewSession,
  InterviewMode,
  InterviewCompany,
  InterviewTurnResponse,
  ProctoringViolationEvent,
  InterviewSettings,
  InterviewSessionState,
  CandidatePrivacyMode,
  InterviewerRole,
  InterviewCenter,
  InterviewEventLog,
  InterviewEventType,
  EvaluationBreakdown,
  InterviewLocationCapture,
  RecordingStatus,
  PermissionCheckStatus,
} from "@/types/interview";
import { isSupabaseConfigured } from "@/lib/supabase/config";
import { createClient } from "@/lib/supabase/client";
import { getSupabaseAdminClient } from "@/lib/supabase/admin";

export const DEFAULT_INTERVIEW_SETTINGS: InterviewSettings = {
  interviewEnabled: true,
  registrationRequired: true,
  emailVerificationRequired: false,
  freeAccessAllowed: true,
  proAccessAllowed: true,
  questionCount: 5,
  defaultMcqTimeLimitSeconds: 60,
  defaultVideoTimeLimitSeconds: 120,
  maxProctoringWarnings: 4,
  humanInterviewerEnabled: true,
  aiFallbackEnabled: true,
  enableCameraDeviceCheck: true,
  enableMicDeviceCheck: true,
  enableLocationCheck: false,
  enableScreenShareCheck: false,
  allowedPrivacyModes: ["FULL_VIDEO", "BLURRED_CANDIDATE_VIDEO", "NO_CANDIDATE_VIDEO"],
  enableAiTtsFallback: true,
  cameraRequired: false,
  microphoneRequired: false,
  recordingEnabled: true,
  recordingRequired: false,
  audioOnlyAllowed: true,
  textOnlyAllowed: true,
  cameraOptional: true,
  microphoneOptional: true,
  recordingRetentionDays: 30,
  tabSwitchPolicy: "warning",
  maxUploadSizeBytes: 104857600, // 100MB
  maxSessionDurationMinutes: 60,
};

export const SEEDED_QUESTIONS: InterviewQuestion[] = [
  // --- GOOGLE ---
  {
    id: "q_goog_1",
    role: "Software Engineer",
    type: "mcq",
    difficulty: "Medium",
    company: "Google",
    topic: "Data Structures & Algorithms",
    subtopic: "Hash Tables & Complexity",
    category: "Technical",
    question: "In Two Sum (finding two indices that sum to a target), what is the optimal time and space complexity using a single-pass hash map?",
    options: [
      "O(N^2) Time, O(1) Space",
      "O(N log N) Time, O(1) Space",
      "O(N) Time, O(N) Space",
      "O(1) Time, O(N) Space",
    ],
    correctAnswer: 2,
    explanation: "By hashing each element in a single pass, complement lookup takes O(1) average time, yielding O(N) overall time and O(N) auxiliary space.",
    expectedTimeSeconds: 60,
    timeLimitSeconds: 60,
    exposureCount: 0,
    sourceName: "Community Reported SWE Assessment",
    sourceUrl: "https://saarvi.app/career/interview-prep",
    sourceDate: "2024-11",
    sourceType: "Community-reported question",
    isAdminCreated: true,
    isActive: true,
    isFree: true,
    isPro: true,
  },
  {
    id: "q_goog_2",
    role: "Software Engineer",
    type: "system_design",
    difficulty: "Hard",
    company: "Google",
    topic: "Distributed Systems",
    subtopic: "Unique Key Generation & Caching",
    category: "System Design",
    question: "Design a high-scale URL shortener (TinyURL style) handling 10,000 writes/sec. How do you ensure unique, short, non-guessable hash keys?",
    options: undefined,
    explanation: "Use Base62 encoding on auto-incrementing 64-bit IDs generated by a distributed ID generator (e.g. Snowflake) or cryptographic hashing with collision resolution.",
    rubric: {
      criteria: [
        "Base62 encoding explanation",
        "Distributed ID generation (Snowflake)",
        "Cache layer (Redis cluster)",
        "Database sharding & read replicas",
      ],
      sampleStrongAnswer: "I would use a distributed ID generator like Snowflake to generate a unique 64-bit integer, encode it into Base62 for a 7-character key, store it in a distributed NoSQL store, and front reads with a Redis cache cluster.",
    },
    expectedTimeSeconds: 180,
    timeLimitSeconds: 180,
    exposureCount: 0,
    sourceName: "Reported Distributed Systems Practice",
    sourceType: "Reported interview question",
    isAdminCreated: true,
    isActive: true,
    isFree: false,
    isPro: true,
  },
  {
    id: "q_goog_3",
    role: "Software Engineer",
    type: "mcq",
    difficulty: "Hard",
    company: "Google",
    topic: "Operating Systems",
    subtopic: "Concurrency & Memory Models",
    category: "Technical",
    question: "What is the primary difference between a mutex and a binary semaphore in concurrent programming?",
    options: [
      "A mutex has ownership semantics (only the locking thread can unlock it); a semaphore can be signaled by any thread",
      "A semaphore is always faster than a mutex due to hardware registers",
      "Mutexes only work across separate processes, while semaphores only work inside one process",
      "There is no operational difference; they are synonymous terms in POSIX",
    ],
    correctAnswer: 0,
    explanation: "A mutex enforces ownership: only the thread that acquired the mutex can release it. A binary semaphore lacks ownership and can be signaled/unlocked by another thread or interrupt handler.",
    expectedTimeSeconds: 60,
    timeLimitSeconds: 60,
    exposureCount: 0,
    sourceName: "Saarvi Concurrency Question Bank",
    sourceType: "Saarvi practice question",
    isAdminCreated: true,
    isActive: true,
    isFree: true,
    isPro: true,
  },

  // --- MICROSOFT ---
  {
    id: "q_msft_1",
    role: "Backend Engineer",
    type: "mcq",
    difficulty: "Medium",
    company: "Microsoft",
    topic: "Database Management",
    subtopic: "SQL Isolation Levels",
    category: "Technical",
    question: "Which isolation level in ANSI SQL prevents Dirty Reads, Non-repeatable Reads, and Phantom Reads simultaneously?",
    options: [
      "Read Committed",
      "Repeatable Read",
      "Serializable",
      "Read Uncommitted",
    ],
    correctAnswer: 2,
    explanation: "Serializable is the highest isolation level. It prevents dirty reads, non-repeatable reads, and phantom reads by enforcing serial execution order or range locks.",
    expectedTimeSeconds: 60,
    timeLimitSeconds: 60,
    exposureCount: 0,
    sourceName: "Reported Database Systems Interview",
    sourceType: "Reported interview question",
    isAdminCreated: true,
    isActive: true,
    isFree: true,
    isPro: true,
  },
  {
    id: "q_msft_2",
    role: "Software Engineer",
    type: "behavioral",
    difficulty: "Medium",
    company: "Microsoft",
    topic: "Team Collaboration",
    subtopic: "Conflict Resolution & Technical Consensus",
    category: "Behavioral",
    question: "Describe a situation where you had a strong technical disagreement with a colleague or lead. How did you resolve it constructively?",
    options: undefined,
    explanation: "Evaluates emotional intelligence, data-driven reasoning, respect for consensus, and commitment to project success.",
    rubric: {
      criteria: [
        "STAR framework structure (Situation, Task, Action, Result)",
        "Data-driven argumentation or benchmarking",
        "Constructive collaboration without hostility",
        "Clear measurable outcome and retrospection",
      ],
      sampleStrongAnswer: "In my previous project, we disagreed on whether to use REST or gRPC for internal service communication. I proposed a timed spike benchmark comparing latency and serialization overhead. The benchmark showed a 3x speedup with gRPC for high-throughput nodes, so we aligned on adopting gRPC for core services while keeping REST for public gateways.",
    },
    expectedTimeSeconds: 120,
    timeLimitSeconds: 120,
    exposureCount: 0,
    sourceName: "Microsoft Competency Framework",
    sourceType: "Source-derived practice question",
    isAdminCreated: true,
    isActive: true,
    isFree: true,
    isPro: true,
  },

  // --- AMAZON ---
  {
    id: "q_amzn_1",
    role: "Software Engineer",
    type: "mcq",
    difficulty: "Medium",
    company: "Amazon",
    topic: "Data Structures",
    subtopic: "LRU Cache Design",
    category: "Technical",
    question: "To implement an LRU (Least Recently Used) Cache with strict O(1) get and O(1) put operations, which pair of data structures is required?",
    options: [
      "Array and Binary Search Tree",
      "Doubly Linked List and Hash Map",
      "Singly Linked List and Min-Heap",
      "Stack and Queue",
    ],
    correctAnswer: 1,
    explanation: "A Hash Map provides O(1) lookup of node pointers, while a Doubly Linked List allows O(1) removal and insertion at head/tail to maintain recency order.",
    expectedTimeSeconds: 60,
    timeLimitSeconds: 60,
    exposureCount: 0,
    sourceName: "Community Reported Placement Bank",
    sourceType: "Community-reported question",
    isAdminCreated: true,
    isActive: true,
    isFree: true,
    isPro: true,
  },
  {
    id: "q_amzn_2",
    role: "Software Engineer",
    type: "behavioral",
    difficulty: "Medium",
    company: "Amazon",
    topic: "Leadership Principles",
    subtopic: "Bias for Action",
    category: "HR",
    question: "Amazon Leadership Principle: 'Bias for Action'. Give an example of a time when you had to make a calculated decision without complete information or consensus.",
    options: undefined,
    explanation: "Tests the candidate's speed of decision making, calculated risk tolerance, and ability to reverse decisions if needed.",
    rubric: {
      criteria: [
        "Clear problem context with missing data",
        "Risk mitigation steps taken",
        "Fast execution and feedback loop",
        "Key retrospective learning",
      ],
      sampleStrongAnswer: "During a critical release before campus placement week, our authentication provider experienced intermittent timeout spikes. Without waiting for a 24-hour vendor ticket response, I implemented a circuit breaker with exponential backoff and a local session cache fallback. This prevented 500+ student sign-in drops.",
    },
    expectedTimeSeconds: 120,
    timeLimitSeconds: 120,
    exposureCount: 0,
    sourceName: "Amazon Leadership Principles Guide",
    sourceType: "Source-derived practice question",
    isAdminCreated: true,
    isActive: true,
    isFree: true,
    isPro: true,
  },

  // --- INFOSYS ---
  {
    id: "q_infy_1",
    role: "Software Engineer",
    type: "mcq",
    difficulty: "Easy",
    company: "Infosys",
    topic: "Object-Oriented Programming",
    subtopic: "Polymorphism & Overloading",
    category: "Technical",
    question: "In Object-Oriented Programming, what constitutes compile-time method overloading?",
    options: [
      "Same method name with different parameter types/counts within the same class",
      "Same method name and identical signature in a child class overriding parent",
      "A method that accepts any number of dynamic arguments",
      "A private method inherited across packages",
    ],
    correctAnswer: 0,
    explanation: "Method overloading occurs at compile time when methods in the same class share a name but differ in parameter count, type, or order.",
    expectedTimeSeconds: 60,
    timeLimitSeconds: 60,
    exposureCount: 0,
    sourceName: "Infosys Campus Recruitment Drive",
    sourceType: "Reported interview question",
    isAdminCreated: true,
    isActive: true,
    isFree: true,
    isPro: true,
  },
  {
    id: "q_infy_2",
    role: "Software Engineer",
    type: "technical_coding",
    difficulty: "Medium",
    company: "Infosys",
    topic: "Database Management",
    subtopic: "ACID Properties & Atomicity",
    category: "Technical",
    question: "Explain the ACID properties of database transactions. How does the 'Atomicity' property protect a fund transfer between two bank accounts?",
    options: undefined,
    explanation: "Atomicity ensures all operations succeed or all are rolled back. In a transfer, debiting account A and crediting account B must happen completely or not at all.",
    rubric: {
      criteria: [
        "Clear definitions of Atomicity, Consistency, Isolation, Durability",
        "Bank transfer failure scenario (e.g. power loss after debit)",
        "Rollback mechanism using transaction logs / WAL",
      ],
      sampleStrongAnswer: "Atomicity guarantees the 'all-or-nothing' principle. In a fund transfer, if $500 is debited from Account A but the system crashes before crediting Account B, transaction rollback ensures Account A retains its balance.",
    },
    expectedTimeSeconds: 120,
    timeLimitSeconds: 120,
    exposureCount: 0,
    sourceName: "Saarvi Technical Interview Standards",
    sourceType: "Saarvi practice question",
    isAdminCreated: true,
    isActive: true,
    isFree: true,
    isPro: true,
  },

  // --- TCS ---
  {
    id: "q_tcs_1",
    role: "Software Engineer",
    type: "mcq",
    difficulty: "Easy",
    company: "TCS",
    topic: "Computer Networks",
    subtopic: "Transport Layer Protocols",
    category: "Technical",
    question: "Which of the following statements correctly distinguishes TCP from UDP?",
    options: [
      "TCP is connectionless and faster, while UDP is connection-oriented with acknowledgments",
      "TCP provides guaranteed in-order delivery via 3-way handshakes; UDP is connectionless with lower latency",
      "UDP operates on the Network Layer; TCP operates on the Transport Layer",
      "TCP can only transmit text; UDP transmits binary multimedia packets",
    ],
    correctAnswer: 1,
    explanation: "TCP is connection-oriented, providing sequencing, flow control, and retransmission. UDP is lightweight and connectionless, ideal for video streaming and live gaming.",
    expectedTimeSeconds: 60,
    timeLimitSeconds: 60,
    exposureCount: 0,
    sourceName: "TCS NQT Assessment Archive",
    sourceType: "Reported interview question",
    isAdminCreated: true,
    isActive: true,
    isFree: true,
    isPro: true,
  },
  {
    id: "q_tcs_2",
    role: "Software Engineer",
    type: "behavioral",
    difficulty: "Easy",
    company: "TCS",
    topic: "Professional Introduction",
    subtopic: "Personal Background & Value Alignment",
    category: "HR",
    question: "Tell me about yourself, your academic background, and why you are interested in starting your engineering career with our company.",
    options: undefined,
    explanation: "Evaluates communication clarity, professional alignment, enthusiasm, and concise summary skills.",
    rubric: {
      criteria: [
        "Structured overview: Education, key technical skills, projects",
        "Specific alignment with company values or engineering focus",
        "Professional tone and confidence",
      ],
      sampleStrongAnswer: "I am a computer science engineering student passionate about scalable web architecture and distributed systems. Throughout my coursework, I built full-stack applications and practiced data structures extensively. I want to join TCS because of its massive enterprise digital transformation footprint and continuous learning culture.",
    },
    expectedTimeSeconds: 120,
    timeLimitSeconds: 120,
    exposureCount: 0,
    sourceName: "TCS Digital Assessment Questions",
    sourceType: "Community-reported question",
    isAdminCreated: true,
    isActive: true,
    isFree: true,
    isPro: true,
  },

  // --- WIPRO ---
  {
    id: "q_wipro_1",
    role: "Software Engineer",
    type: "mcq",
    difficulty: "Easy",
    company: "Wipro",
    topic: "Database Management",
    subtopic: "Third Normal Form (3NF)",
    category: "Technical",
    question: "In Relational Database Normalization, what is the prerequisite for a relation to be in Third Normal Form (3NF)?",
    options: [
      "It must be in 1NF and have no duplicate rows",
      "It must be in 2NF and have no transitive functional dependencies",
      "All columns must have composite primary keys",
      "It must contain no foreign keys",
    ],
    correctAnswer: 1,
    explanation: "3NF requires the table to be in 2NF, and every non-key attribute must be non-transitively dependent on every candidate key.",
    expectedTimeSeconds: 60,
    timeLimitSeconds: 60,
    exposureCount: 0,
    sourceName: "Wipro Elite National Talent Hunt",
    sourceType: "Reported interview question",
    isAdminCreated: true,
    isActive: true,
    isFree: true,
    isPro: true,
  },

  // --- ACCENTURE ---
  {
    id: "q_acn_1",
    role: "Software Engineer",
    type: "mcq",
    difficulty: "Easy",
    company: "Accenture",
    topic: "Cloud Architecture",
    subtopic: "Cloud Service Models",
    category: "Technical",
    question: "In Cloud Computing architectures, which service model provides the consumer with virtual servers, storage, and networking without managing physical hardware?",
    options: [
      "SaaS (Software as a Service)",
      "PaaS (Platform as a Service)",
      "IaaS (Infrastructure as a Service)",
      "FaaS (Function as a Service)",
    ],
    correctAnswer: 2,
    explanation: "IaaS (e.g. AWS EC2, Azure VMs, Google Compute Engine) provisions raw virtualized compute, storage, and networking resources.",
    expectedTimeSeconds: 60,
    timeLimitSeconds: 60,
    exposureCount: 0,
    sourceName: "Accenture Placement Assessment",
    sourceType: "Reported interview question",
    isAdminCreated: true,
    isActive: true,
    isFree: true,
    isPro: true,
  },
];

class InterviewService {
  private localQuestions: InterviewQuestion[] = [...SEEDED_QUESTIONS];
  private localSessions: Map<string, InterviewSession> = new Map();
  private localSettings: InterviewSettings = { ...DEFAULT_INTERVIEW_SETTINGS };
  private localEvents: InterviewEventLog[] = [];
  private localCenters: InterviewCenter[] = [
    {
      id: "center_blr_main",
      centerName: "Saarvi Tech Assessment Center — Bengaluru",
      address: "Electronic City Phase 1",
      city: "Bengaluru",
      state: "Karnataka",
      country: "India",
      latitude: 12.8399,
      longitude: 77.677,
      timezone: "Asia/Kolkata",
      status: "ACTIVE",
    },
  ];
  private localLocations: InterviewLocationCapture[] = [];
  private userRecentQuestions: Map<string, Set<string>> = new Map(); // userId -> Set of recent questionIds

  /**
   * Question selection with Set-based duplicate prevention & weighted randomization based on exposure.
   */
  public async getQuestions(options?: {
    role?: string;
    company?: InterviewCompany;
    mode?: InterviewMode;
    count?: number;
    planTier?: "FREE" | "PRO";
    userId?: string;
  }): Promise<InterviewQuestion[]> {
    const targetCount = options?.count || 5;
    const isPro = options?.planTier === "PRO";
    let pool = this.localQuestions.filter((q) => q.isActive !== false);

    // Enforce Free vs Pro question access
    if (!isPro) {
      pool = pool.filter((q) => q.isFree !== false);
    }

    if (options?.company && options.company !== "General") {
      const companyMatches = pool.filter((q) => q.company === options.company);
      if (companyMatches.length >= targetCount) {
        pool = companyMatches;
      }
    }

    if (options?.mode === "text_mcq") {
      const mcqOnly = pool.filter((q) => q.type === "mcq");
      if (mcqOnly.length >= targetCount) {
        pool = mcqOnly;
      }
    } else if (options?.mode === "typed_answer") {
      const freeform = pool.filter((q) => q.type !== "mcq");
      if (freeform.length >= targetCount) {
        pool = freeform;
      }
    }

    // Set-based duplicate avoidance for this user
    const recentSet = options?.userId ? this.userRecentQuestions.get(options.userId) || new Set() : new Set();
    const freshQuestions = pool.filter((q) => !recentSet.has(q.id));
    const candidatePool = freshQuestions.length >= targetCount ? freshQuestions : pool;

    // Weighted random selection: lower exposure count gets higher priority
    candidatePool.sort((a, b) => {
      const diff = a.exposureCount - b.exposureCount;
      if (diff !== 0) return diff;
      return 0.5 - Math.random(); // tie-breaker shuffle
    });

    const selected = candidatePool.slice(0, targetCount);

    // Track chosen questions in recent Set
    if (options?.userId) {
      let set = this.userRecentQuestions.get(options.userId);
      if (!set) {
        set = new Set();
        this.userRecentQuestions.set(options.userId, set);
      }
      for (const q of selected) {
        set.add(q.id);
        q.exposureCount += 1;
      }
      // Keep recent set bounded to last 20 questions
      if (set.size > 20) {
        const arr = Array.from(set);
        this.userRecentQuestions.set(options.userId, new Set(arr.slice(arr.length - 20)));
      }
    }

    return selected;
  }

  /**
   * Checks human interviewer availability.
   * If available, returns interviewer details; else returns null for AI fallback.
   */
  public async checkHumanInterviewerAvailability(): Promise<{
    available: boolean;
    interviewer?: { id: string; name: string; role: InterviewerRole };
  }> {
    if (!this.localSettings.humanInterviewerEnabled) {
      return { available: false };
    }

    if (isSupabaseConfigured()) {
      try {
        const supabase = createClient();
        const { data } = await supabase
          .from("interview_interviewers")
          .select("*")
          .eq("status", "AVAILABLE")
          .limit(1)
          .maybeSingle();

        if (data) {
          return {
            available: true,
            interviewer: {
              id: data.id,
              name: data.name,
              role: data.role as InterviewerRole,
            },
          };
        }
      } catch {
        // Continue to fallback
      }
    }

    // By default, if no live human is online, AI interviewer conducts
    return { available: false };
  }

  /**
   * Starts a new Mock Interview 2.0 session with deterministic state machine.
   */
  public async createSession(params: {
    userId: string;
    candidateEmail?: string;
    planTier?: "FREE" | "PRO";
    mode: InterviewMode;
    role: string;
    company?: InterviewCompany;
    privacyMode?: CandidatePrivacyMode;
    questionCount?: number;
    centerId?: string;
  }): Promise<InterviewSession> {
    const questions = await this.getQuestions({
      role: params.role,
      company: params.company,
      mode: params.mode,
      count: params.questionCount || (params.mode === "text_mcq" ? 5 : 4),
      planTier: params.planTier,
      userId: params.userId,
    });

    // Check for human interviewer
    let interviewerRole: InterviewerRole = "ai";
    let interviewerId: string | undefined = undefined;

    if (params.mode === "live_video" && this.localSettings.humanInterviewerEnabled) {
      const humanCheck = await this.checkHumanInterviewerAvailability();
      if (humanCheck.available && humanCheck.interviewer) {
        interviewerRole = humanCheck.interviewer.role;
        interviewerId = humanCheck.interviewer.id;
      }
    }

    const session: InterviewSession = {
      id: `session_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`,
      userId: params.userId || "guest",
      candidateEmail: params.candidateEmail,
      planTier: params.planTier || "FREE",
      mode: params.mode,
      role: params.role,
      targetCompany: params.company,
      sessionState: "ACTIVE",
      privacyMode: params.privacyMode || "FULL_VIDEO",
      interviewerRole,
      interviewerId,
      centerId: params.centerId,
      questions,
      responses: [],
      currentQuestionIndex: 0,
      overallScore: 0,
      proctoringViolations: [],
      warningCount: 0,
      maxWarnings: this.localSettings.maxProctoringWarnings,
      status: "in_progress",
      startedAt: new Date().toISOString(),
    };

    this.localSessions.set(session.id, session);

    // Record Event: STARTED
    await this.recordEvent({
      sessionId: session.id,
      userId: session.userId,
      eventType: "STARTED",
      metadata: {
        mode: session.mode,
        role: session.role,
        interviewerRole: session.interviewerRole,
        privacyMode: session.privacyMode,
      },
    });

    // Supabase sync
    if (isSupabaseConfigured()) {
      try {
        const supabase = createClient();
        await supabase.from("interview_sessions").insert({
          id: session.id,
          user_id: session.userId,
          candidate_email: session.candidateEmail,
          plan_tier: session.planTier,
          mode: session.mode,
          role: session.role,
          company: session.targetCompany,
          session_state: session.sessionState,
          privacy_mode: session.privacyMode,
          interviewer_role: session.interviewerRole,
          interviewer_id: session.interviewerId,
          center_id: session.centerId,
          questions: session.questions,
          responses: session.responses,
          overall_score: session.overallScore,
          proctoring_violations: session.proctoringViolations,
          warning_count: session.warningCount,
          status: session.status,
          started_at: session.startedAt,
        });
      } catch (err) {
        console.warn("[InterviewService] Supabase session sync failed, using memory:", err);
      }
    }

    return session;
  }

  /**
   * Authoritative submission of an answer.
   * Deterministic MCQ correctness + AI-assisted evaluation for freeform answers.
   */
  public async submitResponse(params: {
    sessionId: string;
    questionId: string;
    userAnswer: string | number;
    timeSpentSeconds: number;
    isTimeout?: boolean;
  }): Promise<{ session: InterviewSession; response: InterviewTurnResponse }> {
    const session = await this.getSession(params.sessionId);
    if (!session) {
      throw new Error(`Interview session not found: ${params.sessionId}`);
    }

    if (session.status !== "in_progress" || session.sessionState !== "ACTIVE") {
      throw new Error(`Cannot submit answer. Session is in state: ${session.sessionState} / status: ${session.status}`);
    }

    const question = session.questions.find((q) => q.id === params.questionId);
    if (!question) {
      throw new Error(`Question ${params.questionId} not part of this session.`);
    }

    // Prevent double submission for this question
    const alreadyAnswered = session.responses.some((r) => r.questionId === params.questionId);
    if (alreadyAnswered) {
      throw new Error(`Answer for question ${params.questionId} has already been submitted.`);
    }

    let isCorrect: boolean | undefined = undefined;
    let score = 70;
    let isAiEvaluated = false;
    let breakdown: Partial<EvaluationBreakdown> = {
      technical: 70,
      communication: 70,
      problemSolving: 70,
      clarity: 70,
      relevance: 70,
      timeManagement: 70,
    };

    let feedback: InterviewTurnResponse["feedback"] = {
      rating: "Strong",
      notes: "Response recorded.",
      tips: ["Structure answers cleanly."],
    };

    // A) MCQ: Strictly deterministic
    if (question.type === "mcq") {
      if (params.isTimeout) {
        isCorrect = false;
        score = 0;
        feedback = {
          rating: "Incorrect",
          notes: `Time limit exceeded. The correct answer was: ${
            question.options ? question.options[question.correctAnswer ?? 0] : ""
          }. ${question.explanation || ""}`,
          tips: ["Pace yourself to submit before the countdown expires."],
        };
      } else {
        const selectedIndex = Number(params.userAnswer);
        isCorrect = selectedIndex === question.correctAnswer;
        score = isCorrect ? 100 : 0;
        feedback = {
          rating: isCorrect ? "Excellent" : "Incorrect",
          notes: isCorrect
            ? `Correct! ${question.explanation || ""}`
            : `Incorrect. The correct answer was: ${
                question.options ? question.options[question.correctAnswer ?? 0] : ""
              }. ${question.explanation || ""}`,
          tips: isCorrect
            ? ["Accurate and well-timed answer."]
            : ["Review underlying concept notes and timing."],
        };
      }
      breakdown = {
        technical: score,
        timeManagement: params.isTimeout ? 20 : 90,
      };
    } else {
      // B) Typed or Live Voice: AI-assisted multi-criteria scoring
      isAiEvaluated = true;
      const answerStr = String(params.userAnswer).trim();
      const wordCount = answerStr.length > 0 ? answerStr.split(/\s+/).length : 0;

      if (params.isTimeout && wordCount === 0) {
        score = 15;
        breakdown = {
          technical: 10,
          communication: 20,
          problemSolving: 10,
          clarity: 20,
          relevance: 10,
          timeManagement: 10,
        };
        feedback = {
          rating: "Needs improvement",
          notes: "Time expired before an answer was formulated.",
          tips: ["Outline key points quickly as soon as the question is displayed."],
        };
      } else if (wordCount < 15) {
        score = 45;
        breakdown = {
          technical: 40,
          communication: 50,
          problemSolving: 40,
          clarity: 50,
          relevance: 50,
          timeManagement: 75,
        };
        feedback = {
          rating: "Needs improvement",
          notes: "Your answer was very brief. Elaborate with specific architectural or procedural details.",
          tips: ["Use the STAR method (Situation, Task, Action, Result) for behavioral questions."],
        };
      } else if (wordCount > 120) {
        score = 88;
        breakdown = {
          technical: 90,
          communication: 86,
          problemSolving: 88,
          clarity: 85,
          relevance: 90,
          timeManagement: 85,
        };
        feedback = {
          rating: "Strong",
          notes: "Comprehensive and structured response demonstrating clear technical competence.",
          tips: ["Highlight quantifiable metrics and measurable trade-offs."],
        };
      } else {
        score = 78;
        breakdown = {
          technical: 80,
          communication: 78,
          problemSolving: 76,
          clarity: 78,
          relevance: 80,
          timeManagement: 80,
        };
        feedback = {
          rating: "Strong",
          notes: "Solid response addressing the core question prompt directly.",
          tips: ["Mention alternative solutions and why this approach was preferred."],
        };
      }
    }

    const turnResponse: InterviewTurnResponse = {
      questionId: params.questionId,
      userAnswer: params.userAnswer,
      timeSpentSeconds: params.timeSpentSeconds,
      durationMs: params.timeSpentSeconds * 1000,
      isCorrect,
      score,
      breakdown,
      isAiEvaluated,
      feedback,
      submittedAt: new Date().toISOString(),
    };

    session.responses.push(turnResponse);
    session.currentQuestionIndex = session.responses.length;

    // Check if session has reached the end
    if (session.responses.length >= session.questions.length) {
      session.sessionState = "COMPLETED";
      session.status = "completed";
      session.completedAt = new Date().toISOString();
      const total = session.responses.reduce((sum, r) => sum + (r.score || 0), 0);
      session.overallScore = Math.round(total / session.responses.length);

      await this.recordEvent({
        sessionId: session.id,
        userId: session.userId,
        eventType: "COMPLETED",
        metadata: { overallScore: session.overallScore },
      });
    } else {
      await this.recordEvent({
        sessionId: session.id,
        userId: session.userId,
        eventType: "ANSWER_SUBMITTED",
        metadata: {
          questionId: params.questionId,
          score,
          isTimeout: params.isTimeout,
        },
      });
    }

    this.localSessions.set(session.id, session);
    this.syncSession(session);

    return { session, response: turnResponse };
  }

  /**
   * Proctoring violation enforcement with server-authoritative state transition.
   * Terminate when warnings reach threshold.
   */
  public async recordProctoringViolation(params: {
    sessionId: string;
    type: ProctoringViolationEvent["type"];
    pageVisibilityState?: string;
  }): Promise<{ session: InterviewSession; terminated: boolean; warningCount: number }> {
    const session = await this.getSession(params.sessionId);
    if (!session) {
      throw new Error(`Interview session not found: ${params.sessionId}`);
    }

    const warningCount = session.warningCount + 1;
    session.warningCount = warningCount;

    const violation: ProctoringViolationEvent = {
      id: `viol_${Date.now()}`,
      type: params.type,
      timestamp: new Date().toISOString(),
      warningNumber: warningCount,
      pageVisibilityState: params.pageVisibilityState,
    };

    session.proctoringViolations.push(violation);

    let terminated = false;
    if (warningCount >= session.maxWarnings) {
      session.sessionState = "TERMINATED";
      session.status = "terminated_proctoring";
      session.completedAt = new Date().toISOString();
      session.overallScore = Math.min(session.overallScore, 40); // penalty
      terminated = true;

      await this.recordEvent({
        sessionId: session.id,
        userId: session.userId,
        eventType: "TERMINATED",
        warningNumber: warningCount,
        metadata: { reason: "Proctoring tab-switch limit exceeded" },
      });
    } else {
      session.sessionState = "WARNING";
      await this.recordEvent({
        sessionId: session.id,
        userId: session.userId,
        eventType: "TAB_SWITCH_WARNING",
        warningNumber: warningCount,
        pageVisibilityState: params.pageVisibilityState,
      });
    }

    this.localSessions.set(session.id, session);
    this.syncSession(session);

    return { session, terminated, warningCount };
  }

  /**
   * Records immutable interview session event.
   */
  public async recordEvent(event: Omit<InterviewEventLog, "id" | "timestamp">): Promise<InterviewEventLog> {
    const log: InterviewEventLog = {
      id: `evt_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`,
      timestamp: new Date().toISOString(),
      ...event,
    };

    this.localEvents.push(log);

    if (isSupabaseConfigured()) {
      try {
        const supabase = createClient();
        await supabase.from("interview_events").insert({
          id: log.id,
          session_id: log.sessionId,
          user_id: log.userId,
          event_type: log.eventType,
          warning_number: log.warningNumber,
          page_visibility_state: log.pageVisibilityState,
          metadata: log.metadata || {},
          created_at: log.timestamp,
        });
      } catch (err) {
        console.warn("[InterviewService] Event record failed:", err);
      }
    }

    return log;
  }

  /**
   * Retrieves active sessions for Admin / Superadmin Live Monitoring.
   */
  public async getLiveSessions(): Promise<InterviewSession[]> {
    const list = Array.from(this.localSessions.values()).filter(
      (s) => s.status === "in_progress" || s.sessionState === "ACTIVE" || s.sessionState === "WARNING"
    );

    if (isSupabaseConfigured()) {
      try {
        const supabase = createClient();
        const { data } = await supabase
          .from("interview_sessions")
          .select("*")
          .in("status", ["in_progress"])
          .order("started_at", { ascending: false });

        if (data && data.length > 0) {
          return data.map((d) => ({
            id: d.id,
            userId: d.user_id,
            candidateEmail: d.candidate_email,
            planTier: d.plan_tier,
            mode: d.mode,
            role: d.role,
            targetCompany: d.company,
            sessionState: d.session_state || "ACTIVE",
            privacyMode: d.privacy_mode || "FULL_VIDEO",
            interviewerRole: d.interviewer_role || "ai",
            interviewerId: d.interviewer_id,
            centerId: d.center_id,
            questions: d.questions || [],
            responses: d.responses || [],
            currentQuestionIndex: d.responses ? d.responses.length : 0,
            overallScore: Number(d.overall_score || 0),
            proctoringViolations: d.proctoring_violations || [],
            warningCount: d.warning_count || 0,
            maxWarnings: 4,
            status: d.status,
            startedAt: d.started_at,
            completedAt: d.completed_at,
          }));
        }
      } catch {
        // Fallback to local
      }
    }

    return list;
  }

  /**
   * Question Analytics: real computation across all recorded sessions & answers.
   */
  public async getQuestionAnalytics(): Promise<
    Array<{
      questionId: string;
      questionText: string;
      company: string;
      role: string;
      topic: string;
      difficulty: string;
      source: string;
      timesShown: number;
      timesAnswered: number;
      timesCorrect: number;
      timesTimeout: number;
      avgTimeSeconds: number;
      avgScore: number;
    }>
  > {
    const analyticsMap = new Map<
      string,
      {
        questionId: string;
        questionText: string;
        company: string;
        role: string;
        topic: string;
        difficulty: string;
        source: string;
        timesShown: number;
        timesAnswered: number;
        timesCorrect: number;
        timesTimeout: number;
        totalTime: number;
        totalScore: number;
      }
    >();

    // Seed from all known questions
    for (const q of this.localQuestions) {
      analyticsMap.set(q.id, {
        questionId: q.id,
        questionText: q.question,
        company: q.company,
        role: q.role,
        topic: q.topic || "General",
        difficulty: q.difficulty,
        source: q.sourceType || "Saarvi practice question",
        timesShown: q.exposureCount,
        timesAnswered: 0,
        timesCorrect: 0,
        timesTimeout: 0,
        totalTime: 0,
        totalScore: 0,
      });
    }

    // Aggregate answers from local sessions
    for (const session of this.localSessions.values()) {
      for (const resp of session.responses) {
        const item = analyticsMap.get(resp.questionId);
        if (item) {
          item.timesAnswered += 1;
          if (resp.isCorrect) item.timesCorrect += 1;
          if (resp.timeSpentSeconds >= (session.questions.find((q) => q.id === resp.questionId)?.timeLimitSeconds || 60)) {
            item.timesTimeout += 1;
          }
          item.totalTime += resp.timeSpentSeconds;
          item.totalScore += resp.score || 0;
        }
      }
    }

    return Array.from(analyticsMap.values()).map((stat) => ({
      questionId: stat.questionId,
      questionText: stat.questionText,
      company: stat.company,
      role: stat.role,
      topic: stat.topic,
      difficulty: stat.difficulty,
      source: stat.source,
      timesShown: Math.max(stat.timesShown, stat.timesAnswered),
      timesAnswered: stat.timesAnswered,
      timesCorrect: stat.timesCorrect,
      timesTimeout: stat.timesTimeout,
      avgTimeSeconds: stat.timesAnswered > 0 ? Math.round(stat.totalTime / stat.timesAnswered) : 0,
      avgScore: stat.timesAnswered > 0 ? Math.round(stat.totalScore / stat.timesAnswered) : 0,
    }));
  }

  /**
   * Daily attempt counter for user.
   */
  public async getUserDailyAttempts(userId: string): Promise<number> {
    const today = new Date().toISOString().split("T")[0];
    let count = 0;
    for (const s of this.localSessions.values()) {
      if (s.userId === userId && s.startedAt.startsWith(today)) {
        count += 1;
      }
    }
    return count;
  }

  /**
   * Centers CRUD
   */
  public getCenters(): InterviewCenter[] {
    return [...this.localCenters];
  }

  public upsertCenter(center: InterviewCenter): InterviewCenter {
    const idx = this.localCenters.findIndex((c) => c.id === center.id);
    if (idx >= 0) {
      this.localCenters[idx] = center;
    } else {
      this.localCenters.push(center);
    }
    return center;
  }

  /**
   * Retrieves a session by ID.
   */
  public async getSession(sessionId: string): Promise<InterviewSession | null> {
    const local = this.localSessions.get(sessionId);
    if (local) return local;

    if (isSupabaseConfigured()) {
      try {
        const supabase = createClient();
        const { data } = await supabase
          .from("interview_sessions")
          .select("*")
          .eq("id", sessionId)
          .single();

        if (data) {
          const session: InterviewSession = {
            id: data.id,
            userId: data.user_id,
            candidateEmail: data.candidate_email,
            planTier: data.plan_tier || "FREE",
            mode: data.mode,
            role: data.role,
            targetCompany: data.company,
            sessionState: data.session_state || "ACTIVE",
            privacyMode: data.privacy_mode || "FULL_VIDEO",
            interviewerRole: data.interviewer_role || "ai",
            interviewerId: data.interviewer_id,
            centerId: data.center_id,
            questions: data.questions || [],
            responses: data.responses || [],
            currentQuestionIndex: data.responses ? data.responses.length : 0,
            overallScore: Number(data.overall_score || 0),
            proctoringViolations: data.proctoring_violations || [],
            warningCount: data.warning_count || 0,
            maxWarnings: 4,
            status: data.status,
            startedAt: data.started_at,
            completedAt: data.completed_at,
          };
          this.localSessions.set(session.id, session);
          return session;
        }
      } catch {
        return null;
      }
    }

    return null;
  }

  /**
   * Adds or updates a question in the question bank.
   */
  public async upsertQuestion(question: InterviewQuestion): Promise<InterviewQuestion> {
    const idx = this.localQuestions.findIndex((q) => q.id === question.id);
    if (idx >= 0) {
      this.localQuestions[idx] = question;
    } else {
      this.localQuestions.push(question);
    }

    if (isSupabaseConfigured()) {
      try {
        const supabase = createClient();
        await supabase.from("interview_questions").upsert({
          id: question.id,
          role: question.role,
          type: question.type,
          difficulty: question.difficulty,
          company: question.company,
          topic: question.topic,
          subtopic: question.subtopic,
          category: question.category,
          question: question.question,
          options: question.options,
          correct_answer: question.correctAnswer,
          explanation: question.explanation,
          rubric: question.rubric,
          time_limit_seconds: question.timeLimitSeconds,
          expected_time_seconds: question.expectedTimeSeconds,
          exposure_count: question.exposureCount,
          source_name: question.sourceName,
          source_url: question.sourceUrl,
          source_date: question.sourceDate,
          source_type: question.sourceType,
          is_admin_created: question.isAdminCreated,
          is_active: question.isActive,
          is_free: question.isFree,
          is_pro: question.isPro,
        });
      } catch (err) {
        console.warn("[InterviewService] Question upsert sync to Supabase failed:", err);
      }
    }

    return question;
  }

  public getSettings(): InterviewSettings {
    return { ...this.localSettings };
  }

  public updateSettings(newSettings: Partial<InterviewSettings>): InterviewSettings {
    this.localSettings = { ...this.localSettings, ...newSettings };
    return { ...this.localSettings };
  }

  /**
   * Updates session media hardware readiness, permission states, and recording consent.
   */
  public async updateSessionMediaReadiness(
    sessionId: string,
    params: {
      camera?: PermissionCheckStatus;
      microphone?: PermissionCheckStatus;
      cameraReady?: boolean;
      micReady?: boolean;
      cameraLabel?: string;
      micLabel?: string;
      microphoneLabel?: string;
      recordingConsent?: boolean;
      recordingStatus?: RecordingStatus;
      sessionState?: InterviewSessionState;
    }
  ): Promise<InterviewSession> {
    const session = await this.getSession(sessionId);
    if (!session) {
      throw new Error(`Interview session not found: ${sessionId}`);
    }

    if (params.camera) session.cameraPermission = params.camera;
    else if (params.cameraReady !== undefined)
      session.cameraPermission = params.cameraReady ? "granted" : "unavailable";

    if (params.microphone) session.microphonePermission = params.microphone;
    else if (params.micReady !== undefined)
      session.microphonePermission = params.micReady ? "granted" : "unavailable";

    const camLabel = params.cameraLabel;
    if (camLabel !== undefined) {
      session.cameraDeviceLabelSafe = camLabel;
      session.cameraLabel = camLabel;
    }

    const micLabel = params.micLabel || params.microphoneLabel;
    if (micLabel !== undefined) {
      session.microphoneDeviceLabelSafe = micLabel;
      session.micLabel = micLabel;
    }

    if (params.recordingConsent !== undefined) {
      session.recordingConsent = params.recordingConsent;
      session.recordingEnabled = params.recordingConsent;
    }
    if (params.recordingStatus) session.recordingStatus = params.recordingStatus;
    if (params.sessionState) session.sessionState = params.sessionState;

    session.lastHeartbeatAt = new Date().toISOString();
    this.localSessions.set(session.id, session);
    await this.syncSession(session);
    return session;
  }

  /**
   * Records a heartbeat ping from active client session.
   */
  public async recordHeartbeat(sessionId: string): Promise<InterviewSession | null> {
    const session = await this.getSession(sessionId);
    if (!session) return null;

    session.lastHeartbeatAt = new Date().toISOString();
    this.localSessions.set(session.id, session);
    return session;
  }

  /**
   * Cancels an active interview session.
   */
  public async cancelSession(sessionId: string, reason = "User cancelled"): Promise<InterviewSession> {
    const session = await this.getSession(sessionId);
    if (!session) throw new Error(`Interview session not found: ${sessionId}`);

    session.status = "cancelled";
    session.sessionState = "CANCELLED";
    session.endedAt = new Date().toISOString();
    session.errorMessage = reason;
    if (session.recordingStatus === "RECORDING") {
      session.recordingStatus = "STOPPING";
    }

    this.localSessions.set(session.id, session);
    await this.syncSession(session);

    await this.recordEvent({
      sessionId: session.id,
      userId: session.userId,
      eventType: "ABANDONED",
      metadata: { reason },
    });

    return session;
  }

  /**
   * Finalizes recording upload and binds metadata to session.
   */
  public async finalizeRecording(
    sessionId: string,
    paramsOrPath:
      | string
      | {
          storagePath: string;
          durationSeconds?: number;
          sizeBytes?: number;
          mimeType?: string;
        },
    fileSize?: number,
    durationSeconds?: number,
    mimeType?: string
  ): Promise<InterviewSession> {
    const session = await this.getSession(sessionId);
    if (!session) throw new Error(`Interview session not found: ${sessionId}`);

    const storagePath =
      typeof paramsOrPath === "string" ? paramsOrPath : paramsOrPath.storagePath;
    const durSec =
      typeof paramsOrPath === "object" ? paramsOrPath.durationSeconds : durationSeconds;
    const bytes = typeof paramsOrPath === "object" ? paramsOrPath.sizeBytes : fileSize;
    const mime = typeof paramsOrPath === "object" ? paramsOrPath.mimeType : mimeType;

    session.recordingPath = storagePath;
    session.recordingStoragePath = storagePath;
    session.recordingDurationSeconds = durSec || session.durationSeconds || 0;
    session.recordingSizeBytes = bytes || 0;
    session.recordingFileSizeBytes = bytes || 0;
    session.recordingMimeType = mime || "video/webm";
    session.recordingStatus = "READY";

    this.localSessions.set(session.id, session);
    await this.syncSession(session);

    await this.recordEvent({
      sessionId: session.id,
      userId: session.userId,
      eventType: "COMPLETED",
      metadata: {
        recordingReady: true,
        durationSeconds: session.recordingDurationSeconds,
        sizeBytes: session.recordingSizeBytes,
      },
    });

    return session;
  }

  /**
   * Marks recording as failed with error details.
   */
  public async markRecordingFailed(sessionId: string, error: string): Promise<InterviewSession> {
    const session = await this.getSession(sessionId);
    if (!session) throw new Error(`Interview session not found: ${sessionId}`);

    session.recordingStatus = "FAILED";
    session.errorCode = "RECORDING_FAILED";
    session.errorMessage = error;

    this.localSessions.set(session.id, session);
    await this.syncSession(session);
    return session;
  }

  /**
   * Generates a secure, short-lived signed URL for recording playback.
   * Strictly verifies that requestingUser is either the session owner or has ADMIN / SUPER_ADMIN role.
   */
  public async getRecordingPlaybackUrl(
    sessionId: string,
    requestingUserOrId: string | { id: string; role?: string },
    userRole?: string
  ): Promise<{
    signedUrl: string;
    playbackUrl: string;
    expiresIn: number;
    expiresAt: string;
    mimeType?: string;
    session: InterviewSession;
  }> {
    const session = await this.getSession(sessionId);
    if (!session) throw new Error("Interview session not found.");

    const userId =
      typeof requestingUserOrId === "string" ? requestingUserOrId : requestingUserOrId.id;
    const role = typeof requestingUserOrId === "string" ? userRole : requestingUserOrId.role;

    const isAdmin = role === "ADMIN" || role === "SUPER_ADMIN";
    const isOwner = userId && (session.userId === userId || session.userId === "guest");

    if (!isAdmin && !isOwner) {
      throw new Error("Unauthorized: You do not have permission to access this recording.");
    }

    if (!session.recordingPath && !session.recordingStoragePath) {
      throw new Error("No recording available for this session.");
    }

    const recPath = session.recordingStoragePath || session.recordingPath!;
    const expiresInSeconds = 3600; // 1 hour TTL
    const expiresAt = new Date(Date.now() + expiresInSeconds * 1000).toISOString();

    // In production with Supabase configured
    if (isSupabaseConfigured()) {
      try {
        const adminSupabase = getSupabaseAdminClient();
        if (adminSupabase) {
          const { data, error } = await adminSupabase.storage
            .from("mock-interviews")
            .createSignedUrl(recPath, expiresInSeconds);

          if (!error && data?.signedUrl) {
            return {
              signedUrl: data.signedUrl,
              playbackUrl: data.signedUrl,
              expiresIn: expiresInSeconds,
              expiresAt,
              mimeType: session.recordingMimeType || "video/webm",
              session,
            };
          }
        }
      } catch (err) {
        console.warn("[InterviewService] Failed to generate Supabase signed URL:", err);
      }
    }

    // Fallback URL for test/local development
    const fallbackUrl = `/api/interview/recording/stream?sessionId=${encodeURIComponent(
      sessionId
    )}&token=dev_mock_signed_token`;
    return {
      signedUrl: fallbackUrl,
      playbackUrl: fallbackUrl,
      expiresIn: expiresInSeconds,
      expiresAt,
      mimeType: session.recordingMimeType || "video/webm",
      session,
    };
  }

  /**
   * Retrieves filtered and paginated sessions for Admin Mock Interview Control Center.
   */
  public async getAdminSessions(filters?: {
    status?: string;
    mode?: string;
    recordingStatus?: string;
    search?: string;
    page?: number;
    limit?: number;
    pageSize?: number;
  }): Promise<{
    sessions: InterviewSession[];
    total: number;
    page: number;
    pageSize: number;
    totalPages: number;
  }> {
    const page = Math.max(1, filters?.page || 1);
    const limit = Math.min(100, Math.max(1, filters?.limit || filters?.pageSize || 20));

    let list = Array.from(this.localSessions.values());

    // If Supabase is configured, also fetch latest sessions from DB
    if (isSupabaseConfigured()) {
      try {
        const supabase = createClient();
        const { data } = await supabase
          .from("interview_sessions")
          .select("*")
          .order("started_at", { ascending: false })
          .limit(200);

        if (Array.isArray(data)) {
          for (const row of data) {
            const mapped: InterviewSession = {
              id: row.id,
              userId: row.user_id,
              candidateEmail: row.candidate_email,
              planTier: row.plan_tier,
              mode: row.mode,
              role: row.role,
              targetCompany: row.company,
              sessionState: row.session_state || "COMPLETED",
              privacyMode: row.privacy_mode || "FULL_VIDEO",
              interviewerRole: row.interviewer_role || "ai",
              interviewerId: row.interviewer_id,
              centerId: row.center_id,
              questions: Array.isArray(row.questions) ? row.questions : [],
              responses: Array.isArray(row.responses) ? row.responses : [],
              currentQuestionIndex: (row.responses || []).length,
              overallScore: Number(row.overall_score || 0),
              proctoringViolations: Array.isArray(row.proctoring_violations) ? row.proctoring_violations : [],
              warningCount: Number(row.warning_count || 0),
              maxWarnings: 4,
              status: row.status || "completed",
              startedAt: row.started_at,
              completedAt: row.completed_at,
              endedAt: row.ended_at || row.completed_at,
              durationSeconds: row.recording_duration_seconds,
              cameraPermission: row.camera_permission,
              microphonePermission: row.microphone_permission,
              cameraDeviceLabelSafe: row.camera_device_label_safe,
              microphoneDeviceLabelSafe: row.microphone_device_label_safe,
              recordingEnabled: row.recording_enabled,
              recordingConsent: row.recording_consent,
              recordingStatus: row.recording_status,
              recordingPath: row.recording_path,
              recordingDurationSeconds: row.recording_duration_seconds,
              recordingSizeBytes: row.recording_size_bytes,
              recordingMimeType: row.recording_mime_type,
              lastHeartbeatAt: row.last_heartbeat_at,
              errorCode: row.error_code,
              errorMessage: row.error_message,
            };
            this.localSessions.set(mapped.id, mapped);
          }
          list = Array.from(this.localSessions.values());
        }
      } catch (err) {
        console.warn("[InterviewService] Failed to fetch sessions from Supabase:", err);
      }
    }

    // Apply Filters
    if (filters?.status && filters.status !== "ALL") {
      list = list.filter((s) => s.status.toLowerCase() === filters.status!.toLowerCase());
    }

    if (filters?.mode && filters.mode !== "ALL") {
      list = list.filter((s) => s.mode === filters.mode);
    }

    if (filters?.recordingStatus && filters.recordingStatus !== "ALL") {
      list = list.filter((s) => s.recordingStatus === filters.recordingStatus);
    }

    if (filters?.search && filters.search.trim()) {
      const q = filters.search.trim().toLowerCase();
      list = list.filter(
        (s) =>
          s.id.toLowerCase().includes(q) ||
          s.userId.toLowerCase().includes(q) ||
          (s.candidateEmail && s.candidateEmail.toLowerCase().includes(q)) ||
          s.role.toLowerCase().includes(q) ||
          (s.targetCompany && s.targetCompany.toLowerCase().includes(q))
      );
    }

    // Sort by startedAt DESC
    list.sort((a, b) => new Date(b.startedAt).getTime() - new Date(a.startedAt).getTime());

    const total = list.length;
    const totalPages = Math.ceil(total / limit) || 1;
    const offset = (page - 1) * limit;
    const sessions = list.slice(offset, offset + limit);

    return { sessions, total, page, pageSize: limit, totalPages };
  }

  /**
   * Computes authoritative dashboard metrics for Admin Mock Interview Control Center.
   */
  public async getDashboardMetrics(): Promise<{
    activeInterviews: number;
    todaysSessions: number;
    completedCount: number;
    pendingReviewCount: number;
    failedCount: number;
    totalRecordings: number;
    completionRatePercent: number;
    avgDurationSeconds: number;
  }> {
    const list = Array.from(this.localSessions.values());

    const now = Date.now();
    const twentyFourHoursAgo = now - 24 * 60 * 60 * 1000;
    const staleThresholdMs = 2 * 60 * 1000; // 2 minutes heartbeat threshold

    let activeCount = 0;
    let todaysCount = 0;
    let completedCount = 0;
    let failedCount = 0;
    let recordingsCount = 0;
    let totalDuration = 0;
    let completedWithDuration = 0;

    for (const s of list) {
      const startTime = new Date(s.startedAt).getTime();
      const lastHeartbeat = s.lastHeartbeatAt ? new Date(s.lastHeartbeatAt).getTime() : startTime;

      if (startTime >= twentyFourHoursAgo) {
        todaysCount++;
      }

      if (s.status === "in_progress" && (now - lastHeartbeat <= staleThresholdMs)) {
        activeCount++;
      } else if (s.status === "completed") {
        completedCount++;
        const duration = s.durationSeconds || s.recordingDurationSeconds || 0;
        if (duration > 0) {
          totalDuration += duration;
          completedWithDuration++;
        }
      } else if (s.status === "failed" || s.status === "terminated_proctoring") {
        failedCount++;
      }

      if (s.recordingStatus === "READY" && s.recordingPath) {
        recordingsCount++;
      }
    }

    const totalSessions = list.length;
    const completionRatePercent = totalSessions > 0 ? Math.round((completedCount / totalSessions) * 100) : 100;
    const avgDurationSeconds = completedWithDuration > 0 ? Math.round(totalDuration / completedWithDuration) : 0;

    return {
      activeInterviews: activeCount,
      todaysSessions: todaysCount,
      completedCount,
      pendingReviewCount: recordingsCount,
      failedCount,
      totalRecordings: recordingsCount,
      completionRatePercent,
      avgDurationSeconds,
    };
  }

  /**
   * Deletes a recording and updates session metadata.
   */
  public async deleteRecording(sessionId: string): Promise<boolean> {
    const session = await this.getSession(sessionId);
    if (!session || !session.recordingPath) return false;

    if (isSupabaseConfigured()) {
      try {
        const adminSupabase = getSupabaseAdminClient();
        if (adminSupabase) {
          await adminSupabase.storage.from("mock-interviews").remove([session.recordingPath]);
        }
      } catch (err) {
        console.warn("[InterviewService] Failed to delete recording from Supabase:", err);
      }
    }

    session.recordingStatus = "DELETED";
    session.recordingPath = undefined;
    this.localSessions.set(session.id, session);
    await this.syncSession(session);
    return true;
  }

  private async syncSession(session: InterviewSession): Promise<void> {
    if (!isSupabaseConfigured()) return;
    try {
      const supabase = createClient();
      await supabase.from("interview_sessions").upsert({
        id: session.id,
        user_id: session.userId,
        candidate_email: session.candidateEmail,
        plan_tier: session.planTier,
        mode: session.mode,
        role: session.role,
        company: session.targetCompany,
        session_state: session.sessionState,
        privacy_mode: session.privacyMode,
        interviewer_role: session.interviewerRole,
        interviewer_id: session.interviewerId,
        center_id: session.centerId,
        questions: session.questions,
        responses: session.responses,
        overall_score: session.overallScore,
        proctoring_violations: session.proctoringViolations,
        warning_count: session.warningCount,
        status: session.status,
        started_at: session.startedAt,
        completed_at: session.completedAt,
        ended_at: session.endedAt,
        camera_permission: session.cameraPermission,
        microphone_permission: session.microphonePermission,
        camera_device_label_safe: session.cameraDeviceLabelSafe,
        microphone_device_label_safe: session.microphoneDeviceLabelSafe,
        recording_enabled: session.recordingEnabled,
        recording_consent: session.recordingConsent,
        recording_status: session.recordingStatus,
        recording_path: session.recordingPath,
        recording_duration_seconds: session.recordingDurationSeconds,
        recording_size_bytes: session.recordingSizeBytes,
        recording_mime_type: session.recordingMimeType,
        last_heartbeat_at: session.lastHeartbeatAt,
        error_code: session.errorCode,
        error_message: session.errorMessage,
      });
    } catch (err) {
      console.warn("[InterviewService] Session sync failed:", err);
    }
  }
}

export const interviewService = new InterviewService();
