-- =========================================================================
-- Migration 033: Canonical Verified Opportunities Seed & Safety Reports Hardening
-- 1. Updates job_reports reason check constraint to include DUPLICATE
-- 2. Upserts 12 canonical Tier A Saarvi Verified Opportunities into job_opportunities
--    Ensuring they are immediately viewable, active, unexpired, and verifiable
-- =========================================================================

-- 1. HARDEN JOB REPORTS REASON CHECK
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables WHERE table_name = 'job_reports'
  ) THEN
    ALTER TABLE public.job_reports DROP CONSTRAINT IF EXISTS job_reports_reason_check;
    ALTER TABLE public.job_reports ADD CONSTRAINT job_reports_reason_check
      CHECK (reason IN ('FAKE_JOB', 'EXPIRED', 'WRONG_COMPANY', 'BROKEN_LINK', 'MISLEADING_INFO', 'PAYMENT_REQUIRED', 'SUSPICIOUS', 'DUPLICATE', 'OTHER'));
  END IF;
END $$;

-- 2. SEED AUTHORITATIVE TIER A SAARVI VERIFIED OPPORTUNITIES
INSERT INTO public.job_opportunities (
  id,
  type,
  title,
  company_name,
  company_logo_url,
  location,
  country,
  remote_type,
  employment_type,
  experience_level,
  description,
  skills,
  responsibilities,
  qualifications,
  benefits,
  salary_min,
  salary_max,
  salary_currency,
  salary_period,
  salary_text,
  posted_at,
  deadline,
  source_name,
  source_url,
  source_job_id,
  provider_job_id,
  apply_url,
  apply_options,
  provider,
  source_verified,
  verification_status,
  verification_tier,
  status,
  visibility,
  featured,
  canonical_job_key,
  data_origin,
  record_state,
  review_state,
  publication_state,
  verification_state,
  enrichment_state,
  created_at,
  updated_at
) VALUES
(
  'opp_seed_atlassian_swe_fresher_remote',
  'JOB',
  'Associate Software Engineer (Team Collaboration)',
  'Atlassian',
  'https://www.atlassian.com/favicon.ico',
  'Remote (India)',
  'India',
  'remote',
  'full-time',
  'fresher',
  'Atlassian is hiring Associate Software Engineers in India to work on Jira, Confluence, and Bitbucket. This role is remote-eligible with competitive salary, stock options, and comprehensive mentorship.',
  ARRAY['Java', 'Kotlin', 'React', 'TypeScript', 'Microservices', 'REST APIs'],
  ARRAY['Collaborate with cross-functional teams to build reliable features', 'Write unit and integration tests', 'Participate in code reviews and architecture discussions'],
  ARRAY['Bachelor''s or Master''s degree in Computer Science or related field', 'Strong analytical and problem-solving skills'],
  ARRAY['Remote Work Flexibility', 'Competitive Equity & Health Benefits', 'Learning Allowance'],
  1600000,
  2200000,
  'INR',
  'yearly',
  'INR 1600000 - 2200000',
  '2026-03-25T12:00:00.000Z',
  '2027-01-15T23:59:59.000Z',
  'Saarvi Verified',
  'https://www.atlassian.com/company/careers',
  'atlassian_swe_fresher',
  'atlassian_swe_fresher',
  'https://www.atlassian.com/company/careers',
  '[]'::jsonb,
  'admin_manual',
  TRUE,
  'verified',
  'SAARVI_VERIFIED',
  'PUBLISHED',
  'public',
  TRUE,
  'atlassian|associate software engineer (team collaboration)|remote (india)',
  'ADMIN',
  'ACTIVE',
  'APPROVED',
  'PUBLISHED',
  'PASSED',
  'COMPLETED',
  NOW(),
  NOW()
),
(
  'opp_seed_flipkart_sde_intern_blr',
  'INTERNSHIP',
  'Software Development Engineer Intern (Supply Chain)',
  'Flipkart',
  'https://www.flipkart.com/favicon.ico',
  'Bengaluru, Karnataka, India',
  'India',
  'onsite',
  'internship',
  'fresher',
  'Work on India''s largest e-commerce supply chain and fulfillment algorithms at Flipkart. You will collaborate with engineering teams to optimize delivery logistics, warehouse sorting, and dynamic product catalogs.',
  ARRAY['Java', 'Data Structures', 'Algorithms', 'System Design', 'MySQL'],
  ARRAY['Develop low-latency supply chain microservices', 'Analyze fulfillment metrics and optimize inventory queues'],
  ARRAY['Enrolled in B.Tech/B.E. in CS/IT/ECE graduating in 2026 or 2027', 'Proficiency in Java or C++'],
  ARRAY['Pre-Placement Offer (PPO) Opportunity', 'Monthly Stipend', 'Corporate Housing Support'],
  70000,
  90000,
  'INR',
  'monthly',
  'INR 70000 - 90000',
  '2026-03-24T09:30:00.000Z',
  '2026-11-30T23:59:59.000Z',
  'Saarvi Verified',
  'https://www.flipkartcareers.com/',
  'flipkart_sde_intern',
  'flipkart_sde_intern',
  'https://www.flipkartcareers.com/',
  '[]'::jsonb,
  'admin_manual',
  TRUE,
  'verified',
  'SAARVI_VERIFIED',
  'PUBLISHED',
  'public',
  TRUE,
  'flipkart|software development engineer intern (supply chain)|bengaluru, karnataka, india',
  'ADMIN',
  'ACTIVE',
  'APPROVED',
  'PUBLISHED',
  'PASSED',
  'COMPLETED',
  NOW(),
  NOW()
),
(
  'opp_seed_ibm_aiml_intern_blr',
  'INTERNSHIP',
  'AI & Machine Learning Research Intern',
  'IBM India Research',
  'https://www.ibm.com/favicon.ico',
  'Bengaluru, Karnataka, India',
  'India',
  'hybrid',
  'internship',
  'fresher',
  'IBM Research India in Bengaluru invites final-year students and fresh graduates to work on cutting-edge generative AI models, code evaluation benchmarks, and enterprise LLM deployment pipelines.',
  ARRAY['Python', 'PyTorch', 'TensorFlow', 'NLP', 'Machine Learning', 'Hugging Face'],
  ARRAY['Conduct research experiments on transformer models', 'Publish findings or contribute to open-source AI frameworks'],
  ARRAY['Strong mathematical foundations in linear algebra and probability', 'Familiarity with deep learning architectures'],
  ARRAY['Research Mentorship from IBM Fellows', 'Publication Assistance', 'Flexible Hybrid Work'],
  50000,
  75000,
  'INR',
  'monthly',
  'INR 50000 - 75000',
  '2026-03-23T11:00:00.000Z',
  '2026-12-15T23:59:59.000Z',
  'Saarvi Verified',
  'https://www.ibm.com/careers/in-en',
  'ibm_aiml_intern_blr',
  'ibm_aiml_intern_blr',
  'https://www.ibm.com/careers/in-en',
  '[]'::jsonb,
  'admin_manual',
  TRUE,
  'verified',
  'SAARVI_VERIFIED',
  'PUBLISHED',
  'public',
  TRUE,
  'ibm india research|ai & machine learning research intern|bengaluru, karnataka, india',
  'ADMIN',
  'ACTIVE',
  'APPROVED',
  'PUBLISHED',
  'PASSED',
  'COMPLETED',
  NOW(),
  NOW()
),
(
  'opp_seed_phonepe_associate_swe_blr',
  'JOB',
  'Associate Software Engineer (UPI & Merchant Platform)',
  'PhonePe',
  'https://www.phonepe.com/favicon.ico',
  'Bengaluru, Karnataka, India',
  'India',
  'onsite',
  'full-time',
  'fresher',
  'PhonePe is looking for associate software engineers to join our high-throughput payment infrastructure teams. You will work on real-time transaction processing handling billions of transactions per month with sub-100ms latency.',
  ARRAY['Java', 'Spring Boot', 'MySQL', 'Kafka', 'Redis', 'Distributed Systems'],
  ARRAY['Build highly resilient transaction switches', 'Implement idempotent API integrations with banking partners'],
  ARRAY['B.Tech/B.E. in Computer Science', 'Strong data structures and system architecture fundamentals'],
  ARRAY['Comprehensive Health Insurance', 'Annual Wellness Allowance', 'Stock Grants'],
  1200000,
  1700000,
  'INR',
  'yearly',
  'INR 1200000 - 1700000',
  '2026-03-21T09:00:00.000Z',
  '2027-04-30T23:59:59.000Z',
  'Saarvi Verified',
  'https://www.phonepe.com/careers/',
  'phonepe_associate_swe',
  'phonepe_associate_swe',
  'https://www.phonepe.com/careers/',
  '[]'::jsonb,
  'admin_manual',
  TRUE,
  'verified',
  'SAARVI_VERIFIED',
  'PUBLISHED',
  'public',
  TRUE,
  'phonepe|associate software engineer (upi & merchant platform)|bengaluru, karnataka, india',
  'ADMIN',
  'ACTIVE',
  'APPROVED',
  'PUBLISHED',
  'PASSED',
  'COMPLETED',
  NOW(),
  NOW()
),
(
  'opp_seed_google_swe_intern_2026',
  'INTERNSHIP',
  'Software Engineering Intern (Summer 2026)',
  'Google',
  'https://www.google.com/favicon.ico',
  'Bengaluru, Karnataka, India',
  'India',
  'hybrid',
  'internship',
  'fresher',
  'Join Google engineering teams in Bengaluru to build global-scale distributed systems, machine learning pipelines, and developer platforms. As an intern, you will work on production code alongside senior engineers and contribute to critical product features.',
  ARRAY['Data Structures', 'Algorithms', 'Java', 'C++', 'Python', 'Problem Solving'],
  ARRAY['Design and implement software components', 'Participate in architectural discussions and code reviews'],
  ARRAY['Currently enrolled in an undergraduate or graduate degree program in Computer Science or related technical field'],
  ARRAY['Competitive Stipend', 'Mentorship Program', 'Relocation Support'],
  80000,
  120000,
  'INR',
  'monthly',
  'INR 80000 - 120000',
  '2026-03-15T09:00:00.000Z',
  '2027-06-30T23:59:59.000Z',
  'Saarvi Verified',
  'https://careers.google.com/jobs/results/',
  'google_swe_intern_blr',
  'google_swe_intern_blr',
  'https://careers.google.com/jobs/results/',
  '[]'::jsonb,
  'admin_manual',
  TRUE,
  'verified',
  'SAARVI_VERIFIED',
  'PUBLISHED',
  'public',
  TRUE,
  'google|software engineering intern (summer 2026)|bengaluru, karnataka, india',
  'ADMIN',
  'ACTIVE',
  'APPROVED',
  'PUBLISHED',
  'PASSED',
  'COMPLETED',
  NOW(),
  NOW()
),
(
  'opp_seed_microsoft_sde1_hyd',
  'JOB',
  'Software Engineer (SDE 1 - Campus Fresher)',
  'Microsoft',
  'https://www.microsoft.com/favicon.ico',
  'Hyderabad, Telangana, India',
  'India',
  'hybrid',
  'full-time',
  'fresher',
  'Microsoft IDC Hyderabad is looking for passionate fresh graduates to build high-scale cloud infrastructure, enterprise collaboration tools in Teams, and Azure AI systems. Responsibilities include system architecture, test automation, and feature delivery.',
  ARRAY['C#', '.NET', 'Data Structures', 'Azure', 'React', 'TypeScript', 'SQL'],
  ARRAY['Develop scalable cloud microservices on Azure', 'Write comprehensive unit tests and automated benchmarks'],
  ARRAY['B.E./B.Tech or M.E./M.Tech/MS in Computer Science or related degree'],
  ARRAY['Stock Options (RSUs)', 'Comprehensive Healthcare', 'Learning Grants'],
  1400000,
  2000000,
  'INR',
  'yearly',
  'INR 1400000 - 2000000',
  '2026-03-16T11:00:00.000Z',
  '2027-08-31T23:59:59.000Z',
  'Saarvi Verified',
  'https://careers.microsoft.com/',
  'msft_sde1_hyd',
  'msft_sde1_hyd',
  'https://careers.microsoft.com/',
  '[]'::jsonb,
  'admin_manual',
  TRUE,
  'verified',
  'SAARVI_VERIFIED',
  'PUBLISHED',
  'public',
  TRUE,
  'microsoft|software engineer (sde 1 - campus fresher)|hyderabad, telangana, india',
  'ADMIN',
  'ACTIVE',
  'APPROVED',
  'PUBLISHED',
  'PASSED',
  'COMPLETED',
  NOW(),
  NOW()
),
(
  'opp_seed_amazon_sde_intern_blr',
  'INTERNSHIP',
  'Software Development Engineer Intern (SDE)',
  'Amazon',
  'https://www.amazon.in/favicon.ico',
  'Bengaluru, Karnataka, India',
  'India',
  'onsite',
  'internship',
  'fresher',
  'Amazon India is hiring SDE Interns for retail systems, logistics routing engines, and AWS service teams. You will design, develop, test, and deploy robust software solutions while collaborating with product managers and principal architects.',
  ARRAY['Java', 'Object-Oriented Programming', 'AWS', 'Algorithms', 'REST APIs'],
  ARRAY['Build highly scalable services using AWS architecture', 'Improve reliability and observability of critical customer paths'],
  ARRAY['Academic standing in CS/IT or relevant technical discipline'],
  ARRAY['Pre-Placement Offer Consideration', 'Monthly Stipend', 'Transport Assistance'],
  80000,
  110000,
  'INR',
  'monthly',
  'INR 80000 - 110000',
  '2026-03-17T08:30:00.000Z',
  '2027-05-31T23:59:59.000Z',
  'Saarvi Verified',
  'https://www.amazon.jobs/',
  'amazon_sde_intern_blr',
  'amazon_sde_intern_blr',
  'https://www.amazon.jobs/',
  '[]'::jsonb,
  'admin_manual',
  TRUE,
  'verified',
  'SAARVI_VERIFIED',
  'PUBLISHED',
  'public',
  TRUE,
  'amazon|software development engineer intern (sde)|bengaluru, karnataka, india',
  'ADMIN',
  'ACTIVE',
  'APPROVED',
  'PUBLISHED',
  'PASSED',
  'COMPLETED',
  NOW(),
  NOW()
),
(
  'opp_seed_razorpay_backend_intern_blr',
  'INTERNSHIP',
  'Backend Engineering Intern (Fintech)',
  'Razorpay',
  'https://razorpay.com/favicon.ico',
  'Bengaluru, Karnataka, India',
  'India',
  'hybrid',
  'internship',
  'fresher',
  'Build robust, ultra-reliable payment processing systems at Razorpay. As an engineering intern, you will contribute to core payment routing, idempotent transaction processing, and developer webhook pipelines using Golang and Node.js.',
  ARRAY['Go', 'Node.js', 'PostgreSQL', 'Redis', 'Distributed Systems', 'REST APIs'],
  ARRAY['Work on transaction gateway pipelines with 99.99% availability targets', 'Build API documentation and testing suites'],
  ARRAY['Strong understanding of databases, transactions, and REST conventions'],
  ARRAY['Fintech Experience', 'Mentorship', 'Competitive Stipend'],
  45000,
  65000,
  'INR',
  'monthly',
  'INR 45000 - 65000',
  '2026-03-18T10:00:00.000Z',
  '2027-04-30T23:59:59.000Z',
  'Saarvi Verified',
  'https://razorpay.com/jobs/',
  'razorpay_be_intern',
  'razorpay_be_intern',
  'https://razorpay.com/jobs/',
  '[]'::jsonb,
  'admin_manual',
  TRUE,
  'verified',
  'SAARVI_VERIFIED',
  'PUBLISHED',
  'public',
  TRUE,
  'razorpay|backend engineering intern (fintech)|bengaluru, karnataka, india',
  'ADMIN',
  'ACTIVE',
  'APPROVED',
  'PUBLISHED',
  'PASSED',
  'COMPLETED',
  NOW(),
  NOW()
),
(
  'opp_seed_swiggy_frontend_intern_remote',
  'INTERNSHIP',
  'Frontend Engineering Intern (React / Next.js)',
  'Swiggy',
  'https://www.swiggy.com/favicon.ico',
  'Remote (India)',
  'India',
  'remote',
  'internship',
  'fresher',
  'Design and implement lightning-fast web experiences for millions of daily consumers and restaurant partners at Swiggy. Focus on web performance, component architecture, responsive design, and micro-frontend state management.',
  ARRAY['React', 'TypeScript', 'Next.js', 'Tailwind CSS', 'Redux', 'Web Performance'],
  ARRAY['Build responsive consumer-facing components', 'Optimize Core Web Vitals across low-bandwidth networks'],
  ARRAY['Strong JavaScript/TypeScript and CSS layout skills'],
  ARRAY['Remote Freedom', 'Food Reimbursements', 'High-Impact Ownership'],
  40000,
  60000,
  'INR',
  'monthly',
  'INR 40000 - 60000',
  '2026-03-19T09:15:00.000Z',
  '2027-03-31T23:59:59.000Z',
  'Saarvi Verified',
  'https://careers.swiggy.com/',
  'swiggy_fe_intern',
  'swiggy_fe_intern',
  'https://careers.swiggy.com/',
  '[]'::jsonb,
  'admin_manual',
  TRUE,
  'verified',
  'SAARVI_VERIFIED',
  'PUBLISHED',
  'public',
  TRUE,
  'swiggy|frontend engineering intern (react / next.js)|remote (india)',
  'ADMIN',
  'ACTIVE',
  'APPROVED',
  'PUBLISHED',
  'PASSED',
  'COMPLETED',
  NOW(),
  NOW()
),
(
  'opp_seed_infosys_specialist_programmer_blr',
  'JOB',
  'Specialist Programmer / Digital Specialist Engineer',
  'Infosys',
  'https://www.infosys.com/favicon.ico',
  'Bengaluru, Karnataka, India',
  'India',
  'hybrid',
  'full-time',
  'fresher',
  'Infosys is hiring high-potential engineering graduates for high-performance roles in cloud engineering, AI application development, and modern enterprise modernization. Requires strong algorithmic foundation and clean coding standards.',
  ARRAY['Java', 'Python', 'Data Structures', 'Algorithms', 'SQL', 'Cloud Basics'],
  ARRAY['Design algorithms and enterprise cloud microservices', 'Participate in client tech solutioning and agile sprints'],
  ARRAY['B.E./B.Tech/M.E./M.Tech/MCA/M.Sc in eligible engineering disciplines'],
  ARRAY['Fast-Track Technical Career Cadre', 'Global Certification Sponsorship'],
  650000,
  950000,
  'INR',
  'yearly',
  'INR 650000 - 950000',
  '2026-03-19T14:00:00.000Z',
  '2027-07-31T23:59:59.000Z',
  'Saarvi Verified',
  'https://www.infosys.com/careers/',
  'infy_sp_fresher_2026',
  'infy_sp_fresher_2026',
  'https://www.infosys.com/careers/',
  '[]'::jsonb,
  'admin_manual',
  TRUE,
  'verified',
  'SAARVI_VERIFIED',
  'PUBLISHED',
  'public',
  TRUE,
  'infosys|specialist programmer / digital specialist engineer|bengaluru, karnataka, india',
  'ADMIN',
  'ACTIVE',
  'APPROVED',
  'PUBLISHED',
  'PASSED',
  'COMPLETED',
  NOW(),
  NOW()
),
(
  'opp_seed_tcs_digital_fresher_pune',
  'JOB',
  'Software Engineer (TCS Digital Cadre)',
  'Tata Consultancy Services (TCS)',
  'https://www.tcs.com/favicon.ico',
  'Pune, Maharashtra, India',
  'India',
  'hybrid',
  'full-time',
  'fresher',
  'TCS Digital cadre invites computer science and engineering freshers to engineer next-generation solutions in enterprise AI, IoT, cybersecurity, and distributed cloud applications.',
  ARRAY['Python', 'Java', 'SQL', 'Git', 'Object-Oriented Programming', 'REST APIs'],
  ARRAY['Develop modern backend microservices and database schemas', 'Deploy CI/CD pipelines to enterprise cloud instances'],
  ARRAY['Graduating engineering freshers with high competitive coding scores'],
  ARRAY['Accelerated Appraisal Cycle', 'Advanced Technology Incubation'],
  700000,
  850000,
  'INR',
  'yearly',
  'INR 700000 - 850000',
  '2026-03-20T10:30:00.000Z',
  '2027-09-30T23:59:59.000Z',
  'Saarvi Verified',
  'https://www.tcs.com/careers',
  'tcs_digital_fresher',
  'tcs_digital_fresher',
  'https://www.tcs.com/careers',
  '[]'::jsonb,
  'admin_manual',
  TRUE,
  'verified',
  'SAARVI_VERIFIED',
  'PUBLISHED',
  'public',
  TRUE,
  'tata consultancy services (tcs)|software engineer (tcs digital cadre)|pune, maharashtra, india',
  'ADMIN',
  'ACTIVE',
  'APPROVED',
  'PUBLISHED',
  'PASSED',
  'COMPLETED',
  NOW(),
  NOW()
),
(
  'opp_seed_zomato_fullstack_intern_ggn',
  'INTERNSHIP',
  'Full Stack Engineering Intern (Node.js + React)',
  'Zomato',
  'https://www.zomato.com/favicon.ico',
  'Gurgaon, Haryana, India',
  'India',
  'hybrid',
  'internship',
  'fresher',
  'Join Zomato engineering to craft delightful food ordering and dining discovery interfaces. You will build user-facing workflows and backend microservices that handle peak dinner rush traffic seamlessly.',
  ARRAY['JavaScript', 'TypeScript', 'Node.js', 'React', 'MongoDB', 'Express'],
  ARRAY['Build fast order discovery frontends and checkout flows', 'Optimize real-time delivery tracking state'],
  ARRAY['Strong fundamentals in full-stack web architectures'],
  ARRAY['Vibrant Campus Culture', 'Daily Dining Credits', 'PPO Potential'],
  45000,
  65000,
  'INR',
  'monthly',
  'INR 45000 - 65000',
  '2026-03-22T10:00:00.000Z',
  '2027-05-15T23:59:59.000Z',
  'Saarvi Verified',
  'https://www.zomato.com/careers',
  'zomato_fs_intern',
  'zomato_fs_intern',
  'https://www.zomato.com/careers',
  '[]'::jsonb,
  'admin_manual',
  TRUE,
  'verified',
  'SAARVI_VERIFIED',
  'PUBLISHED',
  'public',
  TRUE,
  'zomato|full stack engineering intern (node.js + react)|gurgaon, haryana, india',
  'ADMIN',
  'ACTIVE',
  'APPROVED',
  'PUBLISHED',
  'PASSED',
  'COMPLETED',
  NOW(),
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  company_name = EXCLUDED.company_name,
  location = EXCLUDED.location,
  description = EXCLUDED.description,
  skills = EXCLUDED.skills,
  salary_text = EXCLUDED.salary_text,
  salary_min = EXCLUDED.salary_min,
  salary_max = EXCLUDED.salary_max,
  deadline = EXCLUDED.deadline,
  apply_url = EXCLUDED.apply_url,
  source_verified = TRUE,
  verification_status = 'verified',
  verification_tier = 'SAARVI_VERIFIED',
  status = 'PUBLISHED',
  visibility = 'public',
  data_origin = 'ADMIN',
  record_state = 'ACTIVE',
  review_state = 'APPROVED',
  publication_state = 'PUBLISHED',
  verification_state = 'PASSED',
  updated_at = NOW();
